const CLANS = [
  {
    id: "banu-haqim",
    nome: "Banu Haqim",
    alcunhas: ["Assassinos", "Juízes", "Filhos de Haqim"],
    simbolo: "⚖",
    cor: "#8b6914",
    resumo: "Caçadores implacáveis e executores da lei vampírica, os Banu Haqim habitam as sombras entre o julgamento e a execução. Nascidos das areias da Anatólia e do Oriente Médio, eles foram por séculos os braços armados da Camarilla — e também seus inimigos mais temidos.",
    historia: "Os Banu Haqim traçam sua linhagem até Haqim, o Antediluviano que fundou a cidade de Alamut nas montanhas inacessíveis. Por milênios, serviram como assassinos contratados e guardiões da lei entre os imortais, desenvolvendo uma filosofia de julgamento que mistura lei islâmica, filosofia grega e pragmatismo brutal. No passado recente se dividiram entre a Camarilla e o Sabá, mas hoje muitos buscam um terceiro caminho — o da Anarquia ou da independência total.",
    disciplinas: ["Celeridade", "Ofuscação", "Feitiçaria de Sangue"],
    perdicao: "Vingança — os Banu Haqim são consumidos por um senso de justiça que rapidamente degenera em obsessão com punição. Qualquer transgressão percebida exige correção, e o Banu Haqim em Besta é um executor que não distingue culpados de inocentes.",
    fome: "Os Banu Haqim anseiam pelo sangue de outros vampiros. Quando se alimentam de Cainitas, sua Fome diminui extraordinariamente — e o apetite por este sangue mais rico nunca os abandona completamente.",
    citacao: "\"Nenhuma lei existe sem punição. Nenhuma punição existe sem julgamento. E eu sou o juiz.\""
  },
  {
    id: "brujah",
    nome: "Brujah",
    alcunhas: ["Rebeldes", "Iconoclastas", "A Ralé"],
    simbolo: "✊",
    cor: "#c41230",
    resumo: "Filósofos que se tornaram punhos, revolucionários que não conseguem parar de lutar mesmo quando não sabem mais pelo quê — os Brujah são paixão pura encapsulada em carne imortal e raiva ancestral.",
    historia: "Os Brujah outrora foram filósofos-reis que fundaram Cartago, uma utopia onde mortais e imortais coexistiam como iguais. Quando Cartago caiu — destruída pela traição dos Ventrue e pelos exércitos de Roma — algo em cada Brujah quebrou para sempre. Hoje são os rebeldes eternos da Camarilla, frequentemente deixando-a pelo Movimento Anarquista. Sua raiva não é capricho; é memória.",
    disciplinas: ["Potência", "Presença", "Celeridade"],
    perdicao: "Ira — os Brujah sucumbem à Besta mais facilmente que qualquer outro clã. A mínima provocação pode despertar séculos de raiva reprimida. Sua Frenesi é explosivo, destrutivo e frequentemente impossível de parar sem intervenção externa.",
    fome: "Os Brujah anseiam pelo sangue daqueles que se opõem a eles — inimigos, opressores, traidores. A adrenalina de uma luta genuína é o tempero que torna o sangue inebriante.",
    citacao: "\"Toda ordem é uma corrente dourada. Eu prefiro as cicatrizes da liberdade.\""
  },
  {
    id: "gangrel",
    nome: "Gangrel",
    alcunhas: ["Errantes", "Animais", "Os Selvagens"],
    simbolo: "🐺",
    cor: "#4a6b2a",
    resumo: "Solitários e ferozes, os Gangrel são os vampiros mais próximos da besta que carregam dentro de si. Vagantes eternos que preferem a companhia dos lobos à dos príncipes, eles sobrevivem onde outros perecem.",
    historia: "Os Gangrel não têm uma história central — eles têm mil histórias fragmentadas de sobrevivência. Seu Antediluviano, Ennoia, desapareceu nas profundezas da terra em algum momento do passado. Sem pai, sem cidade, sem hierarquia, os Gangrel encontraram liberdade nessa orfandade. Por séculos fizeram parte da Camarilla, mas a deixaram formalmente em 1999. Muitos são Anarcas; muitos mais não pertencem a coisa nenhuma.",
    disciplinas: ["Animalismo", "Fortitude", "Proteanismo"],
    perdicao: "Bestialidade — cada vez que um Gangrel perde o controle para a Besta, ele ganha marcas animais permanentes: olhos de gato, presas de lobo, orelhas pontiagudas. Com tempo suficiente, distinguir o vampiro do animal torna-se impossível.",
    fome: "Os Gangrel preferem o sangue de animais selvagens e caçados — o sangue de presas que lutaram, que correram, que temeram. Sangue colhido passivamente não satisfaz da mesma forma.",
    citacao: "\"Cidades são prisões de pedra. Eu tenho toda a eternidade para ser livre.\""
  },
  {
    id: "hecata",
    nome: "Hecata",
    alcunhas: ["Coveiros", "O Clã da Morte", "Necrômanos"],
    simbolo: "☽",
    cor: "#6b4a8b",
    resumo: "Uma confederação de clãs menores unidos sob o manto da morte, os Hecata são os vampiros que encaram a mortalidade como ciência e religião simultaneamente. Eles não fogem da morte — eles a estudam, a manipulam, a veneram.",
    historia: "Os Hecata são na verdade um clã-confederação, reunindo os antigos Giovanni, os Samedi, os Cappadocianos sobreviventes e outras linhagens ligadas à morte. Os Giovanni traíram e devoraram os Cappadocianos no século XV; a culpa e o karma dessa traição os persegue. Em 2012, as linhagens se reunificaram formalmente como Hecata, reconhecendo sua herança compartilhada e terrível.",
    disciplinas: ["Auspício", "Fortitude", "Oblívio"],
    perdicao: "Necrose — a maldição familiar dos Giovanni: seu beijo causa dor excruciante em vez de êxtase. Mortais raramente sobrevivem à alimentação de um Hecata sem sequelas. A morte os segue literalmente.",
    fome: "Os Hecata anseiam pelo sangue dos moribundos — aqueles no limiar entre a vida e a morte. O sangue de cadáveres frescos também os sustenta, embora seja considerado indelicado.",
    citacao: "\"A morte não é o fim. É apenas a próxima pergunta.\""
  },
  {
    id: "lasombra",
    nome: "Lasombra",
    alcunhas: ["Senhores das Sombras", "A Nobreza Obscura", "Mestres"],
    simbolo: "⚓",
    cor: "#1a1a4a",
    resumo: "Aristocratas das trevas que governaram o Mediterrâneo por milênios, os Lasombra combinam elegância refinada com crueldade absoluta. Fundadores do Sabá, agora divididos — alguns migraram para a Camarilla, trazendo seus segredos sombrios consigo.",
    historia: "Os Lasombra dominaram o mar Mediterrâneo e a Igreja Católica medieval como marionetes. Quando o Sabá foi fundado, eram sua coluna vertebral — seus Antitribu mais refinados tornaram-se os Mestres. Em 2012, após o avanço dos Antu pelos territórios do Sabá, facções significativas dos Lasombra negociaram entrada na Camarilla, pagando um preço de sangue: matar um parente de clã como prova de lealdade.",
    disciplinas: ["Dominação", "Potência", "Oblívio"],
    perdicao: "Arrogância absoluta — os Lasombra acreditam genuinamente que o sofrimento alheio tem valor pedagógico. Eles não refletem em espelhos e não aparecem em câmeras — nem mesmo digitais — o que interpretam como prova de sua natureza além do mundano.",
    fome: "Os Lasombra anseiam pelo poder — pelo sangue daqueles que possuem autoridade, influência ou força de vontade. O sangue de líderes, chefes e figuras de poder os satisfaz de forma ímpar.",
    citacao: "\"As sombras não mentem. É a luz que ilude.\""
  },
  {
    id: "malkavian",
    nome: "Malkavian",
    alcunhas: ["Lunáticos", "O Clã da Lua", "Visionários"],
    simbolo: "🌙",
    cor: "#6b2a6b",
    resumo: "Cada Malkavian carrega uma maldição única: uma desordem mental que os fragmenta, os expande ou os quebra de formas impossíveis de prever. O que mortais chamariam de loucura, os Malkavian chamam de clareza.",
    historia: "Malkavy, o Antediluviano, foi talvez o primeiro vampiro a enxergar a verdade por trás da realidade — e a verdade o destruiu. Sua maldição passou para cada descendente: uma 'derangem' fundamental que molda toda a percepção. Os Malkavian têm existido em todas as seitas, frequentemente subestimados, frequentemente os mais perigosos. Dizem que todos os Malkavian estão conectados por uma 'Rede' telepática que compartilha conhecimento — e loucura.",
    disciplinas: ["Auspício", "Dominação", "Ofuscação"],
    perdicao: "A Derangem — cada Malkavian recebe uma desordem mental profunda no momento do Abraço. Não é interpretação; é parte de sua natureza vampírica. Com tempo e trauma, derangems adicionais se acumulam.",
    fome: "Os Malkavian anseiam por sangue carregado de emoções extremas — terror puro, êxtase absoluto, desespero total. O cotidiano não os satisfaz; eles precisam do extraordinário.",
    citacao: "\"Todos vocês olham para as sombras na parede. Eu olho para o fogo que as cria.\""
  },
  {
    id: "ministry",
    nome: "Ministry",
    alcunhas: ["Serpentes", "Seguidores de Set", "Libertadores"],
    simbolo: "🐍",
    cor: "#8b6914",
    resumo: "Devotos do deus egípcio Set, o Ministry vê a corrupção não como vício mas como sacramento. Eles tentam porque acreditam genuinamente que libertar os outros de suas inibições é um ato de amor.",
    historia: "Os Seguidores de Set se originaram no Egito antigo, servindo ao deus das tempestades e do caos. Por milênios mantiveram templos secretos onde mortais buscavam vícios e libertação. Recentemente se renomearam como Ministry, adotando uma abordagem mais moderna: clubes noturnos, casas de drogas, movimentos de auto-liberação. Seu Antediluviano, Set, teria sido morto por Osíris e agora aguarda ressurreição.",
    disciplinas: ["Presença", "Ofuscação", "Proteanismo"],
    perdicao: "Sensibilidade à luz — os membros do Ministry sofrem com toda e qualquer luz, não apenas a solar. Mesmo luz artificial causa desconforto; eles preferem a escuridão completa e atuam apenas onde a sombra domina.",
    fome: "O Ministry anseia pelo sangue daqueles que sucumbiram à tentação — viciados, corrompidos, aqueles que venderam suas inibições. Quanto mais profunda a queda, mais doce o sangue.",
    citacao: "\"Eu não te corrompo. Eu te mostro quem você sempre foi.\""
  },
  {
    id: "nosferatu",
    nome: "Nosferatu",
    alcunhas: ["Canalhas", "Monstros", "Os Amaldiçoados"],
    simbolo: "🐀",
    cor: "#3a3a3a",
    resumo: "Deformados além do reconhecimento pelo Abraço, os Nosferatu vivem nas margens da sociedade vampírica — nos esgotos, nos subterrâneos, nos lugares que ninguém mais quer. Em compensação, veem e sabem de tudo.",
    historia: "O Antediluviano Nosferatu — chamado de Absimiliard pelos mais antigos — era obcecado com perfeição física. Quando Caim o maldição, a ironia foi total: cada descendente se tornaria uma criatura de pesadelo. Os Nosferatu responderam à sua condição tornando-se os maiores coletores de informação do mundo vampírico. Nenhum segredo permanece escondido por muito tempo em uma cidade com Nosferatu presentes.",
    disciplinas: ["Animalismo", "Ofuscação", "Potência"],
    perdicao: "Deformidade — o Abraço Nosferatu transforma completamente. Não há forma de mascarar a aparência sem Ofuscação; eles violam automaticamente o Mascaramento apenas estando à vista de mortais.",
    fome: "Os Nosferatu preferem o sangue de ratos, animais de esgoto e desabrigados — aqueles que a sociedade descartou, como eles mesmos foram descartados. Mas guardam rancores.",
    citacao: "\"Você me vê e vê um monstro. Eu te vejo e vejo um segredo.\""
  },
  {
    id: "ravnos",
    nome: "Ravnos",
    alcunhas: ["Ilusionistas", "Ciganos", "Os Errantes"],
    simbolo: "🎲",
    cor: "#8b4a14",
    resumo: "Viajantes eternos e mestres da ilusão, os Ravnos sobreviveram à quase extinção durante a Semana dos Pesadelos — e saíram do outro lado diferentes, mais raros e mais perigosos do que antes.",
    historia: "Os Ravnos vinham principalmente do subcontinente indiano e de comunidades Romani, carregando tradições de viagem e magia de ilusão. Em 1999, a Semana dos Pesadelos quase os exterminou: seu Antediluviano acordou, enlouqueceu, e foi destruído por forças mortais e imortais combinadas. Dos milhares de Ravnos existentes, talvez centenas sobreviveram. Cada um deles é agora uma raridade, e carregam o peso dessa perda.",
    disciplinas: ["Animalismo", "Ofuscação", "Presença"],
    perdicao: "Compulsão ao vício — cada Ravnos possui um vício específico ou compulsão que deve ser satisfeita ou resistida ativamente. Roubo, jogo, sedução, mentira compulsiva — cada um tem o seu.",
    fome: "Os Ravnos anseiam pelo sangue de viajantes, forasteiros, aqueles sem lar fixo — espíritos livres como eles mesmos foram antes da calamidade.",
    citacao: "\"A ilusão perfeita é aquela que o alvo constrói para si mesmo.\""
  },
  {
    id: "toreador",
    nome: "Toreador",
    alcunhas: ["Os Degenerados", "Rosas", "Artistas"],
    simbolo: "🌹",
    cor: "#8b1a4a",
    resumo: "Imortais consumidos pela busca da beleza perfeita, os Toreador congelam diante da arte como outros vampiros congelam diante da Besta. Sua maldição é o refinamento absoluto — e o tédio absoluto de tudo que não atinge esse padrão.",
    historia: "Os Toreador sempre estiveram no centro da sociedade vampírica de elite — Príncipos, Primogênitos, árbitros de gosto. Seu Antediluviano permanece misterioso; alguns dizem que foi um artista, outros que foi sua primeira musa. Por séculos financiaram a arte europeia das sombras, transformando o Renascimento, o Barroco, a Belle Époque em playgrounds imortais. Hoje encontram-se igualmente em galerias de arte contemporânea e em estúdios de gravação.",
    disciplinas: ["Auspício", "Celeridade", "Presença"],
    perdicao: "Êxtase estético — diante de algo verdadeiramente belo, um Toreador pode simplesmente parar. Catalepsia por beleza. Essa vulnerabilidade é sua maior fraqueza e seu segredo mais vergonhoso.",
    fome: "Os Toreador anseiam pelo sangue de artistas, criativos, aqueles que produziram algo genuinamente belo. O talento tem sabor.",
    citacao: "\"A imortalidade sem beleza é apenas uma forma mais longa de morrer.\""
  },
  {
    id: "tremere",
    nome: "Tremere",
    alcunhas: ["Bruxos", "O Clã da Torre", "Mágos de Sangue"],
    simbolo: "🔺",
    cor: "#c41230",
    resumo: "O único clã criado deliberadamente, os Tremere são ex-magos medievais que roubaram a imortalidade vampírica através de ritual e traição. Estruturados como uma ordem hermética, eles são ao mesmo tempo os aliados mais valiosos da Camarilla e sua maior fonte de paranoia.",
    historia: "No século XII, o chefe de uma ordem hermética chamado Tremere procurou a imortalidade. Com seus discípulos, ele capturou Saulot — um Antediluviano Salubri — e o devorou. A magia hermética fundiu-se com o sangue vampírico para criar algo novo: a Sangue-feitiçaria. Por séculos, os Tremere mantiveram uma hierarquia piramidal rígida com o Conselho dos Sete no topo. Em 2008, a Segunda Inquisição e um ataque misterioso destruíram quase toda a liderança. O clã sobrevive, mas fragmentado.",
    disciplinas: ["Auspício", "Dominação", "Feitiçaria de Sangue"],
    perdicao: "Vinculação de sangue forçada — os Tremere antigos dominavam a arte de criar laços de sangue involuntários. Embora a prática seja agora proibida, a desconfiança permanece. Todo Tremere carrega o estigma dessa manipulação histórica.",
    fome: "Os Tremere anseiam pelo sangue de outros sobrenaturais — bruxas, lobisomens, fadas, vampiros de outros clãs. Sangue comum parece agua comparado a esse néctar de poder.",
    citacao: "\"O sangue é a maior magia. Tudo mais é apenas gramática.\""
  },
  {
    id: "tzimisce",
    nome: "Tzimisce",
    alcunhas: ["Dragões", "Moldadores", "Bestas Antigas"],
    simbolo: "🐉",
    cor: "#2a4a1a",
    resumo: "Os mais alienígenas dos vampiros, os Tzimisce transcenderam tanto a humanidade quanto a bestialidade. Eles não apenas moldam carne — eles questionam por que a carne deveria ter uma forma fixa. Antigas voivodes dos Cárpatos que tornaram o corpo uma argila eterna.",
    historia: "Os Tzimisce governaram a Europa Oriental como voivodes — príncipes guerreiros — por milênios, sendo venerados e temidos como dragões nos Cárpatos. Fundadores do Sabá junto com os Lasombra, eles abraçaram a Via da Monstruosidade com fervor filosófico. Seu Antediluviano dizem ter-se fundido com a terra da Europa Oriental — literalmente tornado-se parte do solo. Aqueles Tzimisce que migraram para as cidades modernas tornaram-se algo difícil de categorizar.",
    disciplinas: ["Animalismo", "Dominação", "Proteanismo"],
    perdicao: "Arraigamento territorial — os Tzimisce devem dormir cobertos pela terra de seu domínio natal. Longe dela, regeneram-se mais lentamente. Muitos passam séculos presos ao mesmo solo por essa necessidade.",
    fome: "Os Tzimisce anseiam pela carne — não apenas sangue, mas tecido humano. Nos momentos de frenesi mais profundo, devorar é tão atraente quanto beber.",
    citacao: "\"Forma é uma prisão que construímos para nós mesmos. Eu me libertei.\""
  },
  {
    id: "ventrue",
    nome: "Ventrue",
    alcunhas: ["Lordes", "A Nobreza Azul", "Reis Azuis"],
    simbolo: "👑",
    cor: "#14348b",
    resumo: "Reis eternos que acreditam que liderança é um direito de nascimento vampírico, os Ventrue constroem impérios, compram governos e mantêm a Camarilla funcionando com sangue frio e convicções inabaláveis sobre a ordem natural das coisas.",
    historia: "Os Ventrue remontam aos primeiros reis e senadores de Roma. Seu Antediluviano foi um guerreiro e estadista que viu na imortalidade a extensão lógica da aristocracia. Por milênios, os Ventrue controlaram a Camarilla de dentro — a maioria dos Príncipes de cidades importantes é Ventrue. Também controlaram impérios coloniais, corporações multinacionais, e agora navegam a era digital com a mesma confiança que navegaram o feudalismo.",
    disciplinas: ["Dominação", "Fortitude", "Presença"],
    perdicao: "Apetite restrito — cada Ventrue pode beber apenas de um tipo específico de mortal (loiros, atletas, artistas, crianças, idosos, etc.). Tentar beber de alguém fora dessa categoria causa regurgitação imediata.",
    fome: "Os Ventrue anseiam pelo sangue de líderes, de pessoas poderosas, de CEOs e políticos. Quanto mais influência o doador tem no mundo dos vivos, mais satisfatório o sangue.",
    citacao: "\"Nós não governamos porque queremos poder. Nós governamos porque sem nós, tudo desmorona.\""
  }
];
