const CLANS = [
  {id:"banu-haqim",nome:"Banu Haqim",alcunhas:["O Clã da Caça","Filhos de Haqim","Mediadores","Juízes"],simbolo:"⬡",cor:"#8B0000",citacao:"Nenhuma lei pode existir sem punição. Nenhuma punição pode ser aplicada sem julgamento. E nós somos os juízes.",resumo:"Os Juízes dos Banu Haqim estão divididos entre sua sede hereditária por Sangue vampírico e sua paixão pela justiça. Árbitros severos e ferozmente dedicados a defender um código moral, eles Abraçam mortais capazes de avaliar e lidar com ameaças, aplicar leis e tradições e punir transgressores.",historia:"O Sangue é uma lei em si mesmo a partir da perspectiva dos Banu Haqim, comunicando um senso de dever àqueles que o carregam, além da maldição de estarem para sempre vigiando contra a Besta. Banu Haqim de todas as culturas e tradições jurídicas em vida descobrem que seu Sangue os vincula à rigores e à honra. Eles gravitam em torno de uma sociedade ordenada — segundo seu raciocínio, os Amaldiçoados precisam de estrutura para não se perderem em seus impulsos mais baixos e os domínios se tornarem cenários infernais salpicados de sangue. Um motivo comum entre os Banu Haqim é uma linhagem tripartite composta por juízes, feiticeiros de sangue e assassinos de assassinos. As linhagens mais renomadas prometeram lealdade à Camarilla, embora Juízes pragmáticos favoreçam qualquer instituição que melhor sirva à justiça em um determinado domínio.",
  disciplinas:[
    {nome:"Feitiçaria de Sangue",key:"feiticaria",descricao:"Vários métodos e filosofias Haqimitas a respeito da Feitiçaria de Sangue infletem as aplicações práticas da Disciplina, desde fornecer aos seus praticantes habilidades assassinas até aspectos rituais mais versáteis, extraindo segredos de seu próprio Sangue e do de outros."},
    {nome:"Celeridade",key:"celeridade",descricao:"Os Filhos de Haqim usam Celeridade com efeitos aterrorizantes. Muitos são habilidosos em seu uso antes de todas as outras Disciplinas, para confiar na velocidade do julgamento antes que a dúvida possa retardar uma lâmina na garganta."},
    {nome:"Ofuscação",key:"ofuscacao",descricao:"Os Banu Haqim perseguem suas presas sem serem vistos, seja como um meio de se alimentar discretamente ou de desferir a morte final a um alvo sem os riscos desnecessários de um confronto direto."}
  ],
  perdicoes:[{nome:"Vício em Sangue",texto:"Banu Haqim são atraídos por sangue à mostra daqueles que merecem punição. Têm ainda mais dificuldade de parar com sangue vampírico. Teste de Hunger Frenzy 2+Severidade, se falhar não consegue se segurar e comete Diablerie."},{nome:"Sangue Nocivo",texto:"O sangue do Banu Haqim se torna tóxico, impedindo-o de tornar humanos Ghouls ou de usar o próprio sangue para se curar."}],
  fome:{nome:"Julgamento",descricao:"Banu Haqim se tornam compelidos a punir aqueles que ofendam suas crenças pessoais, se alimentando de pelo menos 1 de fome. Falhar no processo causa uma penalidade de -3 até o fim da cena ou até se saciar."}},

  {id:"brujah",nome:"Brujah",alcunhas:["O Clã Erudito","Chusma","Punks","Hipsters","Prometeanos","Rebeldes","Reis-Filósofos","Helenos"],simbolo:"⊘",cor:"#CC2200",citacao:"Toda ordem é uma corrente, às vezes ela vem decorada e cheia de plumas, mas sempre preferimos as cicatrizes da liberdade.",resumo:"O sonho do clã erudito é um mundo onde toda injustiça tenha sido eliminada. Eles dizem que é por amor aos mortais que os lideram contra seus senhores. Na verdade, eles podem simplesmente enfurecer-se contra um Deus distante ou inexistente que nunca poderão combater, contra uma maldição que nunca poderão encerrar.",historia:"O Clã Brujah sempre Abraçou a partir das fileiras daqueles que simpatizam com a contracultura e a revolução. Eles buscam aliados que questionam ideias normativas e, reconhecendo o fogo dos oprimidos, gravitam em direção aos desfavorecidos. A percepção comum coloca punks, membros de gangues, imigrantes desajustados e manifestantes entre os Brujah. Embora o clã inclua um número substancial de marginalizados vocais, seu desejo de rebelião vai tão fundo quanto o fraudador que rouba a própria empresa, ou o advogado que representa os pobres pro bono. Os Brujah filosóficos, conhecidos como Helenos, acreditam que o melhor método para desmantelar o sistema é compreender os sistemas sociais e culturais que permitem que ele exista em primeiro lugar.",
  disciplinas:[
    {nome:"Celeridade",key:"celeridade",descricao:"Os Brujah usam Celeridade para golpear rápido e escapar de revoltas que eles mesmos iniciaram. Eles caçam com ela para arrebatar recipientes nas ruas, alimentando-se deles de forma selvagem, ou para descartar rapidamente um mortal antes de desaparecer na noite."},
    {nome:"Potência",key:"potencia",descricao:"Os Brujah usam Potência como uma arma devastadora, encurtando qualquer confronto com uma finalidade destrutiva. Embora o clã pregue uma conexão com a humanidade, seus membros frequentemente tomam o que querem pela força."},
    {nome:"Presença",key:"presenca",descricao:"Os Brujah usam Presença para conquistar os corações da multidão, virar uma turba ameaçadora contra si mesma ou enviar um oponente perigoso fugindo para a noite. Os intelectuais Brujah preferem se alimentar com Presença para convencer os recipientes a cederem seu sangue voluntariamente."}
  ],
  perdicoes:[{nome:"Temperamento Difícil",texto:"Qualquer dificuldade para reprimir um Frenesi sofre penalidade de -2 para os Brujah, devido à paixão e intensidade em seu sangue."},{nome:"Violência",texto:"Qualquer crítico em dados de fome fazem com que, de alguma forma, o Brujah cause dano (físico, mental ou social) no alvo da ação."}],
  fome:{nome:"Rebelião",descricao:"A fome faz o vampiro ir contra a pessoa que é o status quo da situação, recebendo uma penalidade de -2 até ir contra uma ordem ou uma expectativa. A compulsão termina quando ele consegue fazer alguém mudar de ideia."}},

  {id:"gangrel",nome:"Gangrel",alcunhas:["O Clã da Besta","Animais","Ferais","Selvagens","Bárbaros","Exilados","Lobos","Vira-latas"],simbolo:"🐺",cor:"#5C4033",citacao:"Cidades são prisões de pedra. Se eu tenho uma eternidade pela frente, prefiro ser livre.",resumo:"Uma fome mais antiga que a humanidade arde dentro dos lobos. Cruzando fronteiras entre espécies, nações e domínios com a facilidade de predadores perfeitos, eles pertencem à vida selvagem e a vida selvagem pertence a eles.",historia:"O Clã Gangrel é composto por exilados, andarilhos, trapaceiros e caçadores. Eles fazem seus refúgios nas partes mais pobres da cidade e não sentem vergonha disso. Eles reivindicam poucos domínios como seus, mas não se curvam a nenhum príncipe. Os Gangrel Abraçam a partir das fileiras de sobreviventes e lutadores: líderes de detentos e gangues, exploradores e qualquer gado que veja o mundo como algo a ser atravessado, em vez de algo do qual se esconder. Eles não se importam com aparências ou títulos, mas sim com realizações e reputação. Qualquer mortal capaz de projetar sua vontade sobre os outros, liderar um grupo do desastre ao sucesso ou lutar contra probabilidades impossíveis atrai a atenção do clã.",
  disciplinas:[
    {nome:"Animalismo",key:"animalismo",descricao:"Um Gangrel pode usar Animalismo para adotar um companheiro animal, às vezes chamado de famulato. O companheiro animal pode ser usado para caçar, espiar e atacar. Alguns Gangrel atiçam animais de estimação contra seus donos ou atraem vira-latas para si para uma alimentação rápida."},
    {nome:"Fortitude",key:"fortitude",descricao:"Como guarda-costas e soldados de longa data para os outros clãs, os Gangrel se beneficiaram enormemente da Fortitude. A Disciplina pode dar-lhes uma sensação de destemor, pois permite-lhes caçar em terrenos difíceis e receber balas e lâminas de faca sem preocupação."},
    {nome:"Proteanismo",key:"proteanismo",descricao:"Os Gangrel são conhecidos por seu domínio de Proteanismo, já que poucos outros clãs possuem seus dons. Cruzando a linha entre o vampirismo e a mudança de forma, a Disciplina permite que um Gangrel assuma as propriedades físicas de outra criatura ou altere sua forma física."}
  ],
  perdicoes:[{nome:"Características Bestiais",texto:"Quando em Frenesi, os Gangrel são obrigados a receber um comportamento ou traço animalesco, seja um cheiro, uma característica física, durando até uma noite a mais do que a duração do frenesi."},{nome:"Instinto de Sobrevivência",texto:"Para fazer qualquer ação que colocaria o Gangrel em perigo, ele tem uma penalidade no teste igual sua severidade de perdição."}],
  fome:{nome:"Impulsos Ferais",descricao:"Retornando ao modo feral, conversar fica difícil, roupas são desconfortáveis e argumentações são melhor resolvidas com dentes e garras. Por uma cena recebe uma penalidade de -3 em Manipulação e Inteligência e só podem se comunicar através de frases de palavra única."}},

  {id:"hecata",nome:"Hecata",alcunhas:["Necromantes","Membros-Demônios","Lazarenos","O Clã da Morte"],simbolo:"☠",cor:"#2E4A3E",citacao:"A morte não é o fim, é apenas a próxima pergunta a ser respondida.",resumo:"Uma coleção heterogênea de linhagens vampíricas necromânticas, o clã Hecata está unido na busca de um único assunto: a Morte. Eles são estudantes do pós-vida e ressurreicionistas dos mortos — ou pior. Vendendo seus serviços a quem pagar mais, há poucos que conseguem se esconder da vigilância daqueles que podem invocar e comandar os próprios espíritos dos falecidos.",historia:"Os Hecata são anômalos entre os clãs de Membros, no sentido de que são praticamente uma seita em si mesmos, um clã que consiste em linhagens estranhas e até mesmo em alguns laços familiares genuínos, todos construídos sobre a reverência e a subjugação ocasional da própria morte. Compreendendo desde famílias criminosas do Velho Mundo que adoram ancestrais até sacerdotes que empunham efígies e monstros degenerados comedores de carne, o clã Hecata tem em comum uma fascinação doentia pela matéria mortal entre suas linhagens membras. Um ritual mórbido uniu recentemente essas consanguinidades díspares em um clã unificado propriamente dito. Os Hecata subscrevem uma filosofia cíclica em relação ao Abraço, que simbolizam pelas três faces da Morte, Decomposição e Renascimento.",
  disciplinas:[
    {nome:"Auspício",key:"auspicio",descricao:"Os Hecata frequentemente consideram o Auspício como a percepção do destino. Ler uma aura torna-se um exercício para discernir como as atitudes do indivíduo o guiam em direção ao seu destino. É também uma Disciplina que exige um certo grau de sutileza, desde sentir fantasmas invisíveis até ler a história espiritual de um objeto."},
    {nome:"Fortitude",key:"fortitude",descricao:"Quem melhor para exaltar a durabilidade física da forma morta-viva? A Fortitude pode se manifestar desde a futilidade de retalhar um cadáver já morto até um grande domínio sobre — e evasão de — as próprias leis da Morte."},
    {nome:"Oblívio",key:"oblivio",descricao:"O Oblívio está entre as Disciplinas mais misteriosas, pois pode alcançar além do véu do pós-vida. Através de seu uso, os Hecata podem interrogar um fantasma ou instigá-lo a atormentar um rival. Eles podem apodrecer a carne de um mortal com um toque ou conduzir um gado intrometido a uma recompensa sombria."}
  ],
  perdicoes:[{nome:"Beijo Doloroso",texto:"O beijo de um Hecata é sempre extremamente doloroso. Vítimas resistem violentamente, e mesmo dispostas devem fazer testes para não se debater contra a dor."},{nome:"Decaimento",texto:"Tudo em volta dos Hecata parece estar lentamente apodrecendo, como se emitissem uma radiação tóxica. Comida, plantas e animais padecem em dias quando próximos dos Hecata."}],
  fome:{nome:"Morbidade",descricao:"O vampiro sente uma urgência em transformar algo vivo em morto ou o contrário, sofrendo uma penalidade de -3 para qualquer ação que não envolva esse objetivo."}},

  {id:"lasombra",nome:"Lasombra",alcunhas:["O Clã da Noite","Magistrados","Guardiões","Sombras"],simbolo:"♛",cor:"#1A0A2E",citacao:"Com certeza, serei sempre seu aliado, mas devo me resignar às sombras, caso contrário eles saberão a verdadeira ameaça que nosso poder combinado apresenta.",resumo:"Criaturas sutilmente em desacordo com a realidade mundana, espera-se que os vampiros Lasombra triunfem a qualquer custo. A crueldade é um traço procurado em suas proles, fazendo com que sua reputação de intrusos traidores seja bem merecida. A maioria não busca atenção, preferindo agir como manipuladores, poderes por trás do proverbial trono.",historia:"A partir das sombras, os Guardiões orquestram seus esquemas, puxando as cordas de Membros inferiores, manipulando-os como se fossem marionetes em fios, encenando o jogo de sombras da Luta Eterna. Os Lasombra estimam grandemente as realizações, especialmente em assuntos pelos quais possam ganhar poder sobre os outros. Eles não gostam de riscos, e os Guardiões ganharam, com inteira justiça, uma reputação de planejamento astuto e cálculo frio. Historicamente, os Lasombra influenciaram todas as seitas: rebeldes precoces na Revolta Anarquista, senhores da guerra do Sabá nas Américas e recrutas formidáveis na Camarilla durante esta era moderna da Segunda Inquisição.",
  disciplinas:[
    {nome:"Dominação",key:"dominacao",descricao:"Os Lasombra confiam em sua habilidade de esmagar vontades e comandar obediência sem os afetos gentis que alguns dos Amaldiçoados fingem possuir. A maneira cruel como exercem esta Disciplina nas vítimas frequentemente rende a antipatia de outros Membros."},
    {nome:"Potência",key:"potencia",descricao:"Quando forçados a recorrer à violência física, os Magistrados podem preferir estourar o crânio de um inimigo com as próprias mãos, enfiar uma bota no estômago de um punk ou arrancar uma porta das dobradiças para impor respeito e medo."},
    {nome:"Oblívio",key:"oblivio",descricao:"A habilidade de manipular sombras permite que os Lasombra observem, golpeiem e escapem sem nunca ter que confrontar sua vítima, ou empregar entidades mais sombrias que a morte para o mesmo propósito."}
  ],
  perdicoes:[{nome:"Imagem Distorcida",texto:"As almas perdidas dos Lasombra já têm um pé no abismo. Fotos, vídeos e gravações do vampiro são sempre distorcidas e imperfeitas, o que os torna difíceis de passar despercebidos em detecções."},{nome:"Insensibilidade",texto:"Os Lasombra têm uma facilidade de se perder do seu lado humano. Eles tendem ao lado do místico e do imperdoável. A dificuldade para testes de Remorso tem uma dificuldade aumentada na Severidade."}],
  fome:{nome:"Crueldade",descricao:"Falhar não é uma opção. A próxima ação que falharem após sofrer com a fome causa uma penalidade de -1 em todos os testes até que passem em um teste relevante."}},

  {id:"malkavian",nome:"Malkavian",alcunhas:["O Clã da Lua","Lunáticos","Loucos","Bobos","Oráculos","Dervixes","Visionários","Filhos de Malkav"],simbolo:"☽",cor:"#4A0E6E",citacao:"Não somos palhaços. Todos vocês olham para as sombras e fingem entender o mundo. Nós olhamos para o fogo que produz a sombra e abraçamos o fato de não entendermos.",resumo:"Os psicólogos diagnosticariam os filhos de Malkav com esquizofrenia, depressão, transtorno obsessivo-compulsivo ou transtorno de estresse pós-traumático. Na realidade, eles têm todas essas coisas e nenhuma. Como os loucos sábios da poesia, sua perturbação decorre de ver demais do mundo de uma só vez.",historia:"Há muito tempo existe o equívoco de que poucas famílias de Membros são tão díspares quanto o Clã da Lua. Outros clãs os veem e raciocinam: cada um deles é louco, então por que suas respectivas origens deveriam importar? Para os Malkavianos, as origens importam muito. Um dos dons que os Malkavianos procuram em um mortal é a segunda vista — a habilidade de interpretar sonhos, perceber espíritos ou prever eventos futuros infalivelmente. Eles também são fascinados pelos quebrados — indivíduos que foram mudados por experiências traumáticas. Alguns Malkavianos afirmam que há um fator comum em sua loucura; que estão todos psiquicamente ligados através de um comprimento de onda comunitário conhecido como a teia ou a rede da loucura.",
  disciplinas:[
    {nome:"Auspício",key:"auspicio",descricao:"Os Malkavianos usam Auspício para aguçar seus sentidos, fortalecendo sua visão ou audição a um nível sobrenatural, ou para determinar os medos, ilusões e fraquezas mentais de um mortal."},
    {nome:"Dominação",key:"dominacao",descricao:"Alguns Malkavianos usam Dominação para afastar todas as distrações da mente de uma vítima, cativando-a completamente; outros usam a Disciplina para extrair ou infligir psicoses, através da infame variante conhecida como Demência."},
    {nome:"Ofuscação",key:"ofuscacao",descricao:"Os Malkavianos não anunciam o uso de Ofuscação, permitindo convenientemente que muitos Membros se esqueçam de que eles têm acesso a esta Disciplina. Alguns Malkavianos se escondem nas casas, alas e lares de idosos do gado, observando os rostos adormecidos antes de se alimentarem discretamente."}
  ],
  perdicoes:[{nome:"Perspectiva Fraturada",texto:"A aflição da linhagem de Malkav aflige todos os seus descendentes com pelo menos uma doença mental. Quando um Malkaviano entra em Frenesi ou Compulsão, sofre uma penalidade da Severidade em uma categoria de atributos."},{nome:"Manifestações Não Naturais",texto:"Sempre que um Malkaviano entra em contato com Malkav usando uma disciplina, algo sobrenatural aflige os humanos à sua volta que ficam com medo e receio do vampiro. Além disso, o Malkaviano tem facilidade em perceber estímulos não naturais, mas que raramente são verdadeiros."}],
  fome:{nome:"Ilusão",descricao:"Ao estar sob efeito da fome os sentidos do Malkaviano começam a ficar selvagens, enxergando, ouvindo e sentindo coisas que não necessariamente são verdade. Recebe uma penalidade de -2 em Destreza, Manipulação, Autocontrole e Determinação."}},

  {id:"ministry",nome:"O Ministério",alcunhas:["Serpentes","O Clã da Fé","O Clã das Mentiras","Setitas"],simbolo:"🐍",cor:"#1C3A1C",citacao:"Você me chama de mentiroso, de tentador e de degenerado, mas todos os seus supostos insultos são simplesmente o peso das correntes com as quais você se acorrenta.",resumo:"O Ministério sempre tem algo a oferecer. Este clã, frequentemente semelhante a um culto, recruta aqueles capazes de empregar a tentação como uma arma. Eles Abraçam aqueles com a vontade e os meios para influenciar, enredar e, por fim, libertar seus alvos daquilo que procuram. Para as Serpentes, tudo tem um preço.",historia:"Parte clã, parte culto, o Ministério ocupa um nicho estranho na sociedade dos Membros. Em suas próprias mentes, o Ministério serve ao propósito de libertar os indivíduos de aceitarem acriticamente o fardo do pecado, seja na forma de doutrina religiosa, estigma social ou mesmo as Tradições dos Amaldiçoados. Para a mente do Ministério, questionar é em si um sacramento. Sem o pecado, que valor tem a retidão? O caminho do Ministério é desafiar a moralidade predominante, perguntar por que algo é proibido. Talvez a maior facção do clã tenha se apropriado do deus egípcio Set, com quem os anciões do clã afirmam ter uma conexão ou mesmo consanguinidade — daí o seu apelido de Setitas.",
  disciplinas:[
    {nome:"Ofuscação",key:"ofuscacao",descricao:"Os Membros do Ministério usam esta Disciplina para descobrir as crenças, perspectivas e vícios de vampiros e mortais, para facilitar sua exploração e libertação. Ministros poderosos também costumam usar os rostos de figuras confiáveis e amigos para melhor atrair as presas para seus santuários e templos."},
    {nome:"Presença",key:"presenca",descricao:"Para muitos Ministros nas noites modernas, esta é a sua habilidade favorita, oferecendo um poder com uma sutileza que satisfaz até mesmo os autoproclamados executores da Máscara. As Serpentes usam Presença com grande destreza, empunhando gestos majestosos e discursos ressonantes que tocam os corações de uma congregação."},
    {nome:"Proteanismo",key:"proteanismo",descricao:"Os Ministros usam esta habilidade para impressionar os observadores, mas também se utilizam de suas muitas maneiras inovadoras de escapar do perigo. Eles costumam adotar a forma de uma cobra em vez de a de um lobo, mas podem se fundir com a terra para evitar o sol ao lado de qualquer Gangrel."}
  ],
  perdicoes:[{nome:"Sangue que Ofusca a Luz",texto:"Quando exposto à iluminação direta intensa — seja natural ou artificial — os Ministry são atordoados. Recebem uma penalidade igual a Severidade em qualquer teste enquanto sob o foco da luz. Recebem também dano + Severidade de luz solar."},{nome:"Sangue Frio",texto:"O sangue dos Ministry é o mais distante da vida. Eles só conseguem se passar por humanos corados, comer e beber, caso tenham se alimentado com sangue bom há pelo menos 2 horas."}],
  fome:{nome:"Transgression",descricao:"O vampiro recebe uma penalidade de -2 para qualquer teste que não envolva fazer alguém quebrar uma crença ou ir contra alguma convicção. Termina quando consegue fazer alguém receber uma Mancha."}},

  {id:"nosferatu",nome:"Nosferatu",alcunhas:["Horrores","O Clã dos Escondidos","Ratos de Esgoto","Leprosos","Colmeias","Cascas","Kapos","Mendigos","Orloks"],simbolo:"🐀",cor:"#2B2B2B",citacao:"Podemos não ser bonitos ou capazes de nos misturar com o gado. Não podemos fingir ser nada além de monstros degenerados. Mas isso nos dá perspectivas que faltam a cada um daqueles outros bastardos iludidos. Nós enxergamos os segredos, pois eles residem nas mais profundas e piores das sombras.",resumo:"Para os Nosferatu, o Abraço é uma jornada através da abjeção, à medida que o Sangue do horror deforma gradualmente os tecidos em luta do corpo humano em abominações grotescas. Semanas de dor resultam em deformidades semelhantes a terríveis defeitos congênitos, crescimentos cancerígenos, lesões incapacitantes e feridas semelhantes às de leprosos.",historia:"Os Nosferatu são os mais humanos dos Membros, exibindo sua maldição por fora e não por dentro. Para se misturarem, alguns recorrem ao Sangue para usar os rostos emprestados de suas vítimas ou desaparecer de vista, enquanto outros confiam em próteses e maquiagem pesada. Quando a Segunda Inquisição encontrou a SchreckNET, muitos Membros propuseram secretamente um brinde ao colapso do clã. Mas aqueles que resistiram e prosperaram dominaram as artes do arquivamento seguro, fisicamente e online. Eles reforçaram seus laços existentes com contatos e clientes, e recuperaram firmemente a confiança dos Membros que valorizam um centro de informações centralizado para pesquisas e troca de mensagens secretas.",
  disciplinas:[
    {nome:"Animalismo",key:"animalismo",descricao:"Os Nosferatu valorizam a Disciplina de Animalismo por sua utilidade em aumentar sua rede de espionagem, obter familiares, permitir a entrega de mensagens e conceder a habilidade de repentinamente subjugar um oponente com uma horda de ratos, insetos ou pássaros."},
    {nome:"Ofuscação",key:"ofuscacao",descricao:"Os Nosferatu têm opiniões divididas sobre a Ofuscação, já que a Disciplina permite que eles se misturem com os outros, mas também mascara aquilo que define seu clã. Alguns Nosferatu orgulham-se da sua monstruosidade indisfarçável, enquanto outros fazem todos os esforços para a ocultar."},
    {nome:"Potência",key:"potencia",descricao:"Os Nosferatu usam Potência para neutralizar rapidamente os inimigos. Os Nosferatu compreendem o mérito de golpear e correr, incapacitando um recipiente antes de se alimentar e fugir, ou quebrando a cabeça do Barão Anarquista antes de saltar para longe do seu esconderijo."}
  ],
  perdicoes:[{nome:"Repulsivo",texto:"Nosferatu são horríveis e feios, e sempre têm o traço Repulsivo (-2). Qualquer tentativa de se disfarçar sofre uma penalidade de Severidade."},{nome:"Infestação",texto:"Não importa para onde eles vão, um rastro de insetos, vermes e ratos sempre segue o Nosferatu. Próximo do Refúgio do Nosferatu, todos sofrem uma penalidade Social de -2."}],
  fome:{nome:"Criptofilia",descricao:"Nosferatu são consumidos pela necessidade de descobrir segredos, seja o que for necessário. Eles também se recusam a dividir segredos com os outros. Qualquer ação que não busque um segredo recebe penalidade de -2."}},

  {id:"ravnos",nome:"Ravnos",alcunhas:["Trapaceiros","Corvos","Demolidores","Os Assombrados"],simbolo:"🦅",cor:"#3D1A00",citacao:"A ilusão perfeita é aquela que o alvo cria para ele mesmo.",resumo:"Mestres do direcionamento incorreto, os Ravnos preferem não lutar ou sangrar por algo que podem obter através de meios mais sutis. Eles podem encantar e desaparecer no espaço de um suspiro mortal, e aqueles outrora enganados rapidamente aprendem a questionar seus próprios sentidos quando na companhia de Corvos.",historia:"Um clã quase aniquilado na salva de abertura da Guerra da Gehena, cujas brasas agora brilham mais a cada noite que passa. Outros os conhecem como portadores de mensagens, andarilhos e manipuladores mentais. Seus métodos não são a força bruta, a adoração de multidões ou conspirações meticulosas que duram séculos, mas sim a astúcia e a elegância, o charme artístico e a ilusão direta. Embora os hábitos nômades do clã tornem difícil qualquer tipo de organização adequada, algo como um renascimento Ravnos está se formando. Um conjunto complexo de sinais e marcas, conhecido e ensinado apenas aos membros do clã, ajuda-os a encontrar e identificar uns aos outros.",
  disciplinas:[
    {nome:"Animalismo",key:"animalismo",descricao:"Os Ravnos mantêm uma relação quase afável com os animais, especialmente corvos, raposas, coiotes, aranhas e macacos. A critério do Narrador, reduza em um a Dificuldade para testes de Animalismo que envolvam esses animais."},
    {nome:"Ofuscação",key:"ofuscacao",descricao:"Embora muitos Trapaceiros sejam capazes de desaparecer de vista e permanecer ocultos, o clã também é adepto de estender o uso da Ofuscação para criar alucinações elaboradas e sustentadas."},
    {nome:"Presença",key:"presenca",descricao:"O método padrão quando o charme natural e a persuasão não são suficientes. Poucos Demolidores estão sem pelo menos alguma medida desta Disciplina. Eles fazem uso frequente da Presença para conseguir vítimas em um piscar de olhos."}
  ],
  perdicoes:[{nome:"Amaldiçoado",texto:"O próprio sangue Ravnos queima por dentro se ele dorme sob um mesmo teto mais de uma vez dentro de 7 noites. Rolar dado igual ao nível de Perdição, e cada 10 causa um dano severo quando acontece."},{nome:"Nome Desnascido",texto:"Todo Ravnos abandona seu nome pré-abraço. Saber esse nome real confere uma vantagem contra o vampiro (vantagem de severidade em qualquer teste)."}],
  fome:{nome:"Tentado pelo Destino",descricao:"A fome o torna tentado pelo perigo. Sempre que de cara com um perigo ele tentará resolvê-lo da forma mais perigosa possível. Qualquer tentativa que fuja do perigo causa uma penalidade de -2, que persiste até o problema ser resolvido ou se torne impossível."}},

  {id:"salubri",nome:"Salubri",alcunhas:["Ciclopes","Ladrões de Almas","Dajjals","Prole de Saulot"],simbolo:"👁",cor:"#1A3A5C",citacao:"Fazer o seu refúgio no vale das dores e trilhar para sempre um caminho de espinhos.",resumo:"Com a maior parte de sua espécie perdida para usurpadores mortos-vivos, o altamente desejável Sangue dos caçados Salubri é um prêmio para outros vampiros. Isso, e sua relutância em Abraçar, os torna raros nas noites modernas. Eles frequentemente recrutam aqueles que estão à beira da morte, acreditando que sua maldição pode fornecer aos dignos uma segunda chance.",historia:"Os Salubri indiscutivelmente já nem sequer são um clã, tendo seu progenitor, segundo se conta, sucumbido às presas de um usurpador mais ambicioso que construiu seu próprio Clã Tremere com aquele Sangue roubado. O deles é um legado de tragédia, mas também uma lição amarga na Luta Eterna que se estende por milênios. Cada Salubri carrega um terceiro olho no centro da testa, o indicador de sua linhagem. De acordo com seus costumes, os senhores Salubri Abraçam apenas quando alcançam a Golconda, transmitindo assim sua maldição novamente a cada vez. As crias Salubri são poucas — sussurra-se que apenas sete existem ao mesmo tempo.",
  disciplinas:[
    {nome:"Auspício",key:"auspicio",descricao:"Grande parte da célebre sabedoria dos Salubri vem de serem capazes de perceber além do alcance de Membros menos observadores. Consideradas por uma mente filosófica, as verdades ocultas do mundo se revelam."},
    {nome:"Dominação",key:"dominacao",descricao:"Os Salubri usam Dominação para livrar os outros dos horrores de ser um vampiro ou de testemunhar as atrocidades que os Membros podem cometer. Seja apagando memórias perturbadoras ou fortalecendo os indivíduos contra as consequências indesejadas de suas ações."},
    {nome:"Fortitude",key:"fortitude",descricao:"Um clã tão desprezado precisa de todas as vantagens possíveis para sobreviver às noites modernas, e os Salubri também aprenderam a manifestar sua própria resistência como um benefício para o bem-estar dos outros."}
  ],
  perdicoes:[{nome:"Caçado",texto:"O sangue dos Salubri é especialmente apetitoso para os outros vampiros. Além de serem caçados, outros vampiros têm dificuldade a resistir a testes de parar de se alimentar do alvo."},{nome:"Ascetismo",texto:"O sangue dos Salubri só funciona bem quando a besta permite. Quando a fome do vampiro está em 1 ou 2, ele tem uma dificuldade igual a severidade para realizar qualquer disciplina que precisa de testes."},{nome:"Terceiro Olho",texto:"Ao passar pelo Abraço, todo Salubri recebe o terceiro olho em sua testa. Sempre que um Salubri utiliza uma disciplina, seu terceiro olho sangra uma quantidade equivalente ao nível da disciplina, podendo provocar frenesi de fome em vampiros próximos."}],
  fome:{nome:"Empatia Afetiva",descricao:"Quando a besta é acordada, seja pela fome ou pela situação, o Salubri é tomado por uma empatia relacionada a algum problema que alguém está passando na cena. O Salubri volta toda sua atenção para resolver a questão. Fazer qualquer ação que não envolva isso sofre uma penalidade de Severidade."}},

  {id:"toreador",nome:"Toreador",alcunhas:["Divas","O Clã da Rosa","Degenerados","Artistas","Prostitutas","Arikelitas","Hedonistas","Sensitivos","Pervertidos"],simbolo:"🌹",cor:"#8B0066",citacao:"A imortalidade sem beleza é apenas uma forma mais longa de morrer.",resumo:"Amaldiçoadas por sua sensualidade desenfreada, as divas são obcecadas pela perfeição estética. Mas descartar os Toreador como pervertidos devassos ou artistas superficiais é o último erro que um Membro cometerá na vida. A beleza é poder, e o amor pode fazer qualquer um fazer praticamente qualquer coisa.",historia:"O Clã Toreador sempre pregou a seletividade em seus rituais do Abraço. Os anciões do clã enfatizam repetidas vezes que o clã necessita de pioneiros entre as artes e todos os tipos de vanguarda. Por esta razão, muitos Toreador emergem das fileiras de artistas talentosos. Para os Toreador, a arte abrange todas as formas de entretenimento e estimulação. O clã corteja os maiores atores, cantores, escritores, bailarinos e até profissionais do sexo. Apesar do costume de Abraçar apenas os melhores, a fixação dos Toreador pela beleza e inocência fez com que muitas divas criassem um neófito apressadamente, resultando em hedonistas superficiais e sucessos de uma nota só. O clã ainda se mantém no topo, liderando a Camarilla ao lado dos Ventrue e Tremere.",
  disciplinas:[
    {nome:"Auspício",key:"auspicio",descricao:"Os Toreador estão sempre à caça de experiências requintadas e usam Auspício para identificar os recipientes mais suscetíveis e aqueles que possam, através dos seus sentimentos e temperamento, oferecer novos sabores e sensações ao bebedor durante a alimentação."},
    {nome:"Celeridade",key:"celeridade",descricao:"Os Toreador afirmam que não são combatentes, mas poucos se movem tão rapidamente quanto o degenerado que usa Celeridade para cortar um oponente em pedaços antes mesmo que ele tenha tempo de sacar sua arma. Os Toreador frequentemente usam Celeridade para aprimorar habilidades artísticas ou performáticas."},
    {nome:"Presença",key:"presenca",descricao:"Os Toreador dominam a Disciplina de Presença, frequentemente usando-a em conjunto com Auspício para manipular as emoções de Membros e do gado. A Presença pode garantir um público apreciativo ou causar o fracasso de outro artista."}
  ],
  perdicoes:[{nome:"Fixação Estética",texto:"O desejo incansável pela beleza é tão intenso que causa sofrimento. Se a personagem se encontra em uma situação de beleza prejudicada ele sofre uma penalidade igual a Severidade para qualquer teste envolvendo Disciplina."},{nome:"Empatia Agonizante",texto:"A maldição de sentir demais. Ao causar danos a pessoas que o vampiro sente empatia, o Toreador sente a dor igual, e muitas vezes o dano é replicado no próprio corpo, como cicatrizes e lesões."}],
  fome:{nome:"Obsessão",descricao:"A fome torna o vampiro obcecado por algum objeto ou pessoa especialmente bela. Quando capturado o vampiro não consegue pensar em outra coisa e só sabe falar sobre aquilo. Qualquer ação não relacionada ao objeto recebe uma penalidade de -2. Dura até o fim da cena ou destruição do objeto."}},

  {id:"tremere",nome:"Tremere",alcunhas:["Usurpadores","Feiticeiros","Herméticos","Taumaturgos","Transgressores","O Clã Partido","Bruxas de Sangue"],simbolo:"⊙",cor:"#6B0000",citacao:"Nunca fomos nobres. Nobreza não vem do sangue, magia vem. O restante é apenas gramática.",resumo:"Um mago Hermético na Romênia do século VIII, Tremere era o líder de uma cabala de praticantes de magia temidos por sua obsessão por conhecimento e poder. Incapaz de aceitar a própria mortalidade, Tremere instigou os experimentos mágicos mais aterrorizantes já conduzidos, condenando a si mesmo e a seus seguidores a um inferno criado por eles mesmos.",historia:"Depois que a Segunda Inquisição destruiu a Capela Primária em Viena em 2008, os Tremere caíram de eminências pardas para personae non gratae em muitas regiões. A arrogância da Pirâmide fizera com que os Usurpadores conquistassem poucos amigos. Sem a Pirâmide ordenando-os em posições e valores, os feiticeiros encontram-se competindo com seus companheiros Membros e, cada vez mais, uns com os outros por qualquer coisa que possa permitir-lhes recuperar parte do seu antigo poder. O termo mago mercenário está se tornando cada vez mais difundido.",
  disciplinas:[
    {nome:"Auspício",key:"auspicio",descricao:"Os Tremere usam Auspício para perceber as auras dos outros, procurar evidências de essências mágicas e objetos importantes deixados para trás, e para comunicar uns com os outros através de vastas distâncias sem medo de serem ouvidos."},
    {nome:"Feitiçaria de Sangue",key:"feiticaria",descricao:"Mestres taumaturgos, a experiência dos Tremere em magia de sangue faz deles um pilar valioso, embora desconfiado, da Camarilla. Usando Feitiçaria de Sangue, eles podem desferir ataques devastadores contra a mente e o corpo de um oponente."},
    {nome:"Dominação",key:"dominacao",descricao:"Os Tremere farão quase tudo por conhecimento e influência, e Dominação é a Disciplina que permite que eles saiam impunes disso. Ao tentar se alimentar, um Tremere mostrará escassos escrúpulos em usar a Disciplina para forçar um mortal a expor sua garganta."}
  ],
  perdicoes:[{nome:"Sangue Fraco",texto:"Os Tremere não são mais capazes de formar Laços de Sangue com outros vampiros, e é mais difícil que o normal com humanos e ghouls, somando Severidade ao número de noites necessárias."},{nome:"Sangue Roubado",texto:"O Sangue não original da linhagem de Caim faz com que os Tremere tenham mais dificuldades de fazer ações inumanas que seriam comuns e fáceis para outros vampiros, como saltar longas distâncias, correr rápido ou esmagar uma haste de madeira."}],
  fome:{nome:"Perfeccionismo",descricao:"Nada menos que o perfeito satisfaz os Tremere, até o vampiro ter um teste com Sucesso Crítico ou até o final da cena. Ele recebe uma penalidade de -2 para uma ação, -1 para a próxima e zera para a terceira, porém caso a ação alvo mude completamente, a penalidade reinicia."}},

  {id:"tzimisce",nome:"Tzimisce",alcunhas:["Dragões","O Velho Clã","Voivodes","Fomentadores"],simbolo:"🐉",cor:"#003320",citacao:"Não para liderar, não para triunfar, mas para governar — possuir completamente. A forma é uma prisão. Eu me libertei.",resumo:"Para os Tzimisce, a posse é tudo. Eles visam dominar e possuir o objeto de sua possessividade, guardando-o zelosamente como o dragão de seu nome faria com seu tesouro. Tudo, desde terras, pessoas, cultos, empresas ou gangues, pode cair sob as garras cobiçosas de um Dragão.",historia:"Os encargos do clã têm sido tradicionalmente definidos geograficamente, como uma terra ou um povo regional, mas à medida que as propriedades na Transilvânia diminuem, eles estendem sua obsessão para gangues, redes de negócios ou mesmo unidades militares. Esta possessividade implacável estende-se também à forma física dos Tzimisce, que se consideram os donos definitivos dos seus corpos. Muitos Dragões praticam uma especialização da Disciplina de Metamorfose conhecida como Vicissitude, que lhes permite remodelar seus corpos e os de seus súditos e até de vítimas menos dispostas. Os Tzimisce participaram vigorosamente na Revolta Anarquista e foram um dos clãs fundadores do Sabá.",
  disciplinas:[
    {nome:"Animalismo",key:"animalismo",descricao:"Alguns Tzimisce cultivam o Animalismo como uma extensão da sua unidade com os seus domínios. Outros veem-no como uma ferramenta para melhor comandar hordas de feras inferiores de modo a reivindicar esses domínios. Em qualquer caso, os Tzimisce sentem há muito tempo uma afinidade com os habitantes mais bestiais das suas terras ancestrais."},
    {nome:"Dominação",key:"dominacao",descricao:"A Disciplina perfeita para impor editais através de pura força mental. Dominação não apenas ajuda os Dragões a se apoderarem do objeto de sua obsessão, mas também condiciona servidores de longo prazo a se tornarem extensões da vontade inquestionável do Demônio."},
    {nome:"Proteanismo",key:"proteanismo",descricao:"Como mestres de suas próprias formas físicas, os Tzimisce usam Metamorfose para se forçarem em outras formas. Muitos Tzimisce praticam os métodos da Vicissitude, que lhes permite transcender as formas mecânicas de Metamorfose e tratar os seus próprios corpos e os dos seus súditos como argila primordial."}
  ],
  perdicoes:[{nome:"De Castigo",texto:"Os Tzimisce são ligados a um vínculo — seja com um espaço físico, um grupo ou até algo esotérico. O vampiro precisa gastar seu sono envolvido por seu vínculo, se não o fizer, recebe uma penalidade de Severidade em pontos de Força de Vontade."},{nome:"Cortesia Amaldiçoada",texto:"Quando um Tzimisce entra no Refúgio ou Moradia de outrem, sem ser convidado, ele é inundado por um stress volumoso. Suas Disciplinas sofrem uma penalidade igual a Severidade durante esse stress, mas podem gastar força de vontade para ignorar isso."}],
  fome:{nome:"Cobiça",descricao:"O Tzimisce se torna obcecado com um objeto ou alguém e precisa adicioná-lo aos seus pertences. Qualquer ação que não seja direcionada a esse objetivo sofre uma penalidade de -2. Passa ao conseguir o objetivo ou se torne impossível."}},

  {id:"ventrue",nome:"Ventrue",alcunhas:["O Clã dos Reis","Sangues-Azuis","Tiranos","Senhores da Guerra","Patrícios","Borgias","o Culto de Mithras"],simbolo:"♜",cor:"#00008B",citacao:"Nós não governamos porque queremos poder. Nós governamos porque sem nós, tudo desmorona.",resumo:"Aos seus próprios olhos, apenas o Clã dos Reis tem a contenção, a sabedoria, o controle e o pedigree para liderar sua espécie através da noite. Ao longo de sua trajetória como reis-deuses da antiga Babilônia e lordes e ladys da Idade das Trevas até seus papéis contemporâneos como guardiões de sangue real, acionistas majoritários e apoiadores de fundos de campanha, eles têm sido obcecados pelo impulso de governar.",historia:"O Clã Ventrue há muito tempo lidera a Camarilla, ocupando mais posições de poder do que qualquer outro clã, e eles relutam em abrir mão disso. Os Ventrue acreditam na força da tradição e da linhagem. O Abraço é um dos seus rituais mais importantes, e a escolha da cria afeta a forma como os outros membros do clã tratam o senhor. Os Ventrue, portanto, visam Abraçar pessoas de alto desempenho, gado política ou financeiramente poderoso, ou aqueles com um talento que os diferencie das massas. Os Ventrue são o sistema. Eles estabelecem e mantêm as regras, punindo aqueles que as quebram. A verdade desconfortável é que, sem eles, a Máscara, e a Camarilla com ela, já teriam caído há muito tempo.",
  disciplinas:[
    {nome:"Dominação",key:"dominacao",descricao:"Os Ventrue consideram-se os mestres desta Disciplina, usando-a principalmente para exercer a sua vontade sobre vassalos e sobre o gado. Ao se alimentar, um Ventrue pode ordenar a um mortal que exponha o pescoço, ou usar Dominação para apagar toda a memória de uma alimentação."},
    {nome:"Fortitude",key:"fortitude",descricao:"A Fortitude permite aos Ventrue manterem os seus tronos mesmo quando os exércitos se alinham contra eles, e resistirem a todas as lâminas, balas e bombas. Onde outros Membros podem ficar sem vitae, os Ventrue resistem ao ambiente e saciam a sua Fome."},
    {nome:"Presença",key:"presenca",descricao:"Os Ventrue procuram domar a corte e construir o amor e a devoção dos outros em relação ao seu governo. A Disciplina também é usada pelo Ventrue que quer que os outros vejam a facilidade com que adquire recipientes."}
  ],
  perdicoes:[{nome:"Gostos Refinados",texto:"Quando os Ventrue se alimentam de sangue que não seja de sua preferência, o sangue retorna como uma êmese escarlate. Os métodos de predador dos Ventrue são extremamente específicos, como: somente ruivos, somente suecos ou apenas homossexuais, porém conseguem sentir caso o sangue seja da forma como preferem."},{nome:"Hierarquia",texto:"Os Ventrue sofrem uma penalidade igual a Severidade para usar seus poderes contra vampiros que seriam considerados seus superiores. Além disso, têm que gastar força de vontade para causar dano em vampiros de gerações inferiores."}],
  fome:{nome:"Arrogância",descricao:"Nada os faz parar até que estejam sob controle da situação e comandando os presentes. Há uma penalidade de -2 para ações que não envolvam esse objetivo. Dura até que algum não jogador cumpra uma ordem vindo do Ventrue."}}
];
