const DISCIPLINES = {
  "Animalismo": {
    descricao: "Disciplina que permite ao vampiro se comunicar e controlar animais, além de manipular a Besta em outras criaturas — incluindo vampiros.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Laço Familiar",resumo:"Crie um laço especial com um companheiro animal específico.",custo:"Alimentar Animal + 3 Noites",dados:"Carisma + Empatia",resist:"-",mecanica:"Só pode ter um vínculo familiar por vez. Vínculo só é perdido na morte do animal. O animal tem um pouco de sangue de vampiro então suas funções básicas são ligeiramente aumentadas.",duracao:"Morte"},
      {nivel:1,amalgama:"-",nome:"Sentir a Besta",resumo:"Sinta hostilidade e efeitos sobrenaturais.",custo:"Passivo",dados:"Determinação + Animalismo",resist:"Autocontrole + Subterfúgio",mecanica:"Uma vitória permite sentir o nível de hostilidade do alvo, saber se é um vampiro ou outra criatura sobrenatural, assim como seu nível de fome.",duracao:"-"},
      {nivel:2,amalgama:"Ausp. 1",nome:"Mensageiro Animal",resumo:"Use seu familiar para transmitir uma mensagem para alguém.",custo:"CS",dados:"-",resist:"-",mecanica:"Caso o alvo precise ser encontrado o animal fará um teste de Determinação + Sobrevivência/Manha.",duracao:"Busca"},
      {nivel:2,amalgama:"-",nome:"Atavismo",resumo:"Reverta a situação de um animal adestrado para seu estado feral.",custo:"CS",dados:"Autocontrole + Animalismo",resist:"-",mecanica:"É preciso ter contato físico/visual/auditivo.",duracao:"Dif.Teste + 1 horas/rodadas"},
      {nivel:2,amalgama:"-",nome:"Sussurros Selvagens",resumo:"Forma uma linha de comunicação de duas mãos com um animal.",custo:"CS",dados:"Manipulação/Carisma + Animalismo",resist:"-",mecanica:"A ação não tem CS se for utilizada no próprio familiar.",duracao:"Cena"},
      {nivel:3,amalgama:"Domin. 1",nome:"Comandar Mensageiro",resumo:"Utilize suas habilidades de Dominação através de seu familiar.",custo:"Vide Habil.",dados:"Vide Habil.",resist:"Vide Habil.",mecanica:"O nível da habilidade de Dominação não pode ultrapassar o seu nível de Animalismo.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Suculência Animal",resumo:"Passa a se sacear com animais sem penalidades.",custo:"Passivo",dados:"-",resist:"-",mecanica:"Um quadrado a mais de fome é conquistado ao se alimentar de animais. Recebe -2 de penalização de Potência de Sangue ao se alimentar de animais.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Praga Feral",resumo:"Marque um alvo para ser o alvo de animais próximos.",custo:"CS",dados:"Manipulação + Animalismo",resist:"Autocontrole + Empatia",mecanica:"O alvo é penalizado por Dif.Teste em atributos Mentais e Sociais e fica extremamente fácil de rastrear.",duracao:"Uma noite"},
      {nivel:3,amalgama:"-",nome:"Repressão Bestial",resumo:"Force um vampiro a abrir mão da besta ou deixe um mortal letárgico.",custo:"CS",dados:"Carisma + Animalismo",resist:"Vigor + Determinação",mecanica:"Contra vampiros dura 1 + Dif.Teste turnos/horas. Cancela uma disciplina específica de um vampiro.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Odor da Presa",resumo:"Marque e rastreie um mortal que observou uma quebra de Máscara.",custo:"CS",dados:"Determinação + Animalismo",resist:"-",mecanica:"Algumas horas em sucesso. Um dia completo se houve sucesso crítico.",duracao:"Cena"},
      {nivel:3,amalgama:"Ofusc. 2",nome:"Enxame Não Vivo",resumo:"Seus efeitos de Animalismo se extendem a enxames de insetos.",custo:"Passivo",dados:"-",resist:"-",mecanica:"Enxames são tratados como alvo único para todos os efeitos.",duracao:"-"},
      {nivel:4,amalgama:"-",nome:"Consumar Espírito",resumo:"Possua o controle do corpo de um animal.",custo:"CS",dados:"Manipulação + Animalismo",resist:"-",mecanica:"É gratuito e sem duração ao ser usado em seu familiar.",duracao:"Cena / -"},
      {nivel:4,amalgama:"-",nome:"Controlar Matilha",resumo:"Influencie animais de uma grande área a se comportar da maneira desejada.",custo:"x CS",dados:"Autocontrole + Animalismo",resist:"-",mecanica:"A quantidade de sucessos determina o quanto os animais serão influenciados. Pode testar mais CS para aumentar a área.",duracao:"Noite"},
      {nivel:5,amalgama:"-",nome:"Domínio Animal",resumo:"Comande ativamente grupos de animais.",custo:"2 CS",dados:"Carisma + Animalismo",resist:"-",mecanica:"Os animais te obedecem claramente dentro de seus limites físicos. Os animais não vêm ao seu encontro, precisam já estar na cena.",duracao:"Cena / Conclusão"},
      {nivel:5,amalgama:"-",nome:"Coagir o Temperamento",resumo:"Aumente ou diminua a dificuldade para resistir à Frenesi para vampiros à sua volta.",custo:"CS",dados:"Manipulação + Animalismo",resist:"-",mecanica:"Cada Dif.Teste aumenta/diminui em 1 a dificuldade.",duracao:"Efeito"},
      {nivel:5,amalgama:"-",nome:"Trazer a Besta",resumo:"Transfira seu frenesi ou terror para uma vítima.",custo:"CS",dados:"Raciocínio + Animalismo",resist:"Autocontrole + Determinação",mecanica:"Não pode transferir frenesi causado pela fome.",duracao:"Duração do Frenesi"},
      {nivel:5,amalgama:"-",nome:"Caminhar Espiritual",resumo:"Prolonga o efeito de Consumar Espírito entre animais.",custo:"-",dados:"-",resist:"-",mecanica:"A habilidade pode ser transferida sem você precisar retornar ao seu corpo, de animal para animal.",duracao:"-"}
    ]
  },
  "Auspício": {
    descricao: "Disciplina da percepção extrassensorial. Permite ao vampiro ler auras, sentir o sobrenatural, rastrear alvos e até mesmo ler mentes.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Sentidos Aguçados",resumo:"Aumente o natural dos sentidos.",custo:"-",dados:"Raciocínio + Determinação",resist:"-",mecanica:"Se passar no teste, adicione Auspícios para todos os testes que envolvam algum dos sentidos. Duração pode aumentar em 1 sempre que acabar com o uso de Força de Vontade.",duracao:"Dif.Teste + 1 hora/turno"},
      {nivel:1,amalgama:"-",nome:"Sentir o Invisível",resumo:"Sinta atividades sobrenaturais a sua volta.",custo:"-",dados:"Raciocínio/Determinação + Auspícios",resist:"Parada Relevante",mecanica:"Raciocínio é usado contra alvos em Ofuscação vs Raciocínio + Ofuscação. Buscas normais são ativadas passivamente e envolvem Determinação.",duracao:"-"},
      {nivel:2,amalgama:"Fort. 1",nome:"Panacea",resumo:"Cure Força de Vontade e acalme os nervos do alvo.",custo:"CS",dados:"Autocontrole + Auspícios",resist:"-",mecanica:"Precisa entrar em contato com o sangue do alvo. Se usado em mais de um alvo na mesma noite, cada subsequente custa Força de Vontade igual a metade do número de sucessos.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Premonição",resumo:"Tenha uma visão do futuro.",custo:"- / CS",dados:"Determinação + Auspícios",resist:"-",mecanica:"O narrador pode ativar essa habilidade como um sexto sentido de graça ou pode ser ativada com um CS, para usar a habilidade focada em um alvo.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Revelar Temperamento",resumo:"Sinta o cheiro da Ressonância de um alvo.",custo:"CS",dados:"Inteligência + Auspícios",resist:"Autocontrole + Subterfúgio",mecanica:"Revela a característica do sangue de um humano e, se usado em um vampiro, revela as características e tempo de sua última alimentação.",duracao:"Cena"},
      {nivel:2,amalgama:"Dom. 1",nome:"Caçada Enervante",resumo:"Rastreie um alvo.",custo:"CS",dados:"Determinação + Auspícios",resist:"-",mecanica:"Precisa estar em contato com sangue/objeto pessoal do alvo. A vítima pode fazer um teste de Raciocínio + Percepção para perceber que está sendo rastreada.",duracao:"Dif.Teste Noites"},
      {nivel:3,amalgama:"Anim. 2",nome:"Visão do Verme",resumo:"Receba ou envie sentidos para um animal.",custo:"CS",dados:"Determinação + Animalismo",resist:"-",mecanica:"Funciona em grupos de animais, mas sem filtro.",duracao:"Cena"},
      {nivel:3,amalgama:"Obl. 1",nome:"Falha Fatal",resumo:"Encontre uma fraqueza específica do alvo.",custo:"CS",dados:"Inteligência + Auspícios",resist:"Autocontrole/Vigor + Subterfúgio",mecanica:"Autocontrole é usado para fraquezas mentais e Vigor para fraquezas físicas.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Mapear a Alma",resumo:"Colha uma informação sobre o alvo.",custo:"CS",dados:"Inteligência + Auspícios",resist:"Autocontrole + Subterfúgio",mecanica:"Pode ser utilizado em um alvo ou em uma multidão.",duracao:"Turno"},
      {nivel:3,amalgama:"-",nome:"Dividir Sentidos",resumo:"Invada a mente do alvo e sinta o que ele está sentindo.",custo:"CS",dados:"Determinação + Auspícios",resist:"-",mecanica:"Você vê, sente, ouve tudo que o alvo percebe mas não consegue influenciar nada disso. O Vampiro escolhe quais e quantos sentidos quer perceber.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Toque do Espírito",resumo:"Ao tocar um objeto inanimado retire informações sobre ele.",custo:"CS",dados:"Inteligência + Auspícios",resist:"-",mecanica:"Pode ser usado em objetos e no solo. Retire informações do que foi feito com o objeto e as emoções e intenções da pessoa que o manipulou.",duracao:"Turno"},
      {nivel:5,amalgama:"-",nome:"Clarividência",resumo:"Expanda sua mente e reúna informações de uma área.",custo:"CS",dados:"Inteligência + Auspícios",resist:"-",mecanica:"O vampiro entra em um transe e consegue sentir as coisas e reunir informações em até uma quadra de distância sobre tudo que estiver acontecendo ali.",duracao:"Transe (Força de Vontade)"},
      {nivel:5,amalgama:"Dom. 3",nome:"Possessão",resumo:"Tome controle a força de um corpo mortal.",custo:"2 CS",dados:"Determinação + Auspícios",resist:"Determinação + Inteligência",mecanica:"Você controla completamente as ações do alvo mortal, porém não consegue ler sua mente ou revisitar memórias.",duracao:"Até Finalizar"},
      {nivel:5,amalgama:"-",nome:"Telepatia",resumo:"Leia mentes e transmita pensamentos.",custo:"CS / + FdV",dados:"Determinação + Auspícios",resist:"Raciocínio + Subterfúgio",mecanica:"Não há necessidade de realizar um teste caso só queira transmitir o próprio pensamento. Há custo de CS para ler mentes e se for um vampiro é preciso gastar FdV.",duracao:"Um Minuto por CS"},
      {nivel:5,amalgama:"Dom. 3",nome:"Desenterrar a Alma Bestial",resumo:"Remova uma Mácula ou proteja o alvo de recebê-las.",custo:"2CS + 1 Mácula",dados:"Determinação + Auspícios",resist:"-",mecanica:"A habilidade só funciona em vampiros com Humanidade menor do que a do usuário.",duracao:"Sessão"}
    ]
  },
  "Celeridade": {
    descricao: "Disciplina da velocidade sobrenatural. Permite ao vampiro mover-se, atacar e reagir muito além dos limites humanos.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Graça Felina",resumo:"Passe automaticamente em testes que envolvam equilíbrio.",custo:"-",dados:"-",resist:"-",mecanica:"Não funciona em objetos que não aguentem seu peso.",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Suavidade Fluída",resumo:"Rerrole seu nível de Sangue em testes de Destreza ou Celeridade.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Reflexos Rápidos",resumo:"Tenha seus reflexos amplificados.",custo:"-",dados:"-",resist:"-",mecanica:"Os vampiros não sofrem penalidade contra armas de fogo por não terem cobertura em combates. Reagindo a eventos com presteza sobre-humana.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Rapidez",resumo:"Adicione seu nível de Celeridade para testes fora de combate que envolvam Destreza.",custo:"- / CS",dados:"-",resist:"-",mecanica:"Pode ser usado para se defender em combate, porém custa um CS por rodada.",duracao:"Cena"},
      {nivel:2,amalgama:"-",nome:"Trabalho Ágil",resumo:"Termine um trabalho específico que levaria longas horas em alguns minutos.",custo:"CS",dados:"-",resist:"-",mecanica:"Este poder não funciona durante combate.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Piscadela",resumo:"Encurte a distância até um alvo em um piscar de olhos.",custo:"CS",dados:"Destreza + Atletismo",resist:"-",mecanica:"O usuário só pode se mover em linha reta e talvez faça testes de dificuldade de acordo com o terreno.",duracao:"Turno"},
      {nivel:3,amalgama:"-",nome:"Travessia",resumo:"Mova-se rápido o suficiente para subir em superfícies verticais ou líquidas.",custo:"CS",dados:"Destreza + Atletismo",resist:"-",mecanica:"Há um limite de distância a ser informado pelo narrador.",duracao:"Turno"},
      {nivel:3,amalgama:"-",nome:"Costurar",resumo:"Remova a penalidade de dado ao se defender de múltiplos alvos no mesmo turno de combate.",custo:"CS",dados:"-",resist:"-",mecanica:"O usuário ainda pode adicionar seus dados de Celeridade em todos os testes.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Momento Embaçado",resumo:"Ataques contra o usuário que tenham menos sucessos que seu nível de Celeridade sempre erram automaticamente.",custo:"CS por turno",dados:"-",resist:"-",mecanica:"Funciona passivamente contra poderes que não permitem testes de defesa.",duracao:"Enquanto Ativa"},
      {nivel:4,amalgama:"-",nome:"Rascunho de Elegância",resumo:"Transforma o próprio sangue em uma poção de velocidade para outros vampiros.",custo:"CS",dados:"-",resist:"-",mecanica:"Cada vampiro que beber a poção deve fazer um CS. O alvo ganha nível de Celeridade igual à metade do usuário e todos os poderes que ele tinha até aquele nível.",duracao:"Noite"},
      {nivel:4,amalgama:"Ausp. 2",nome:"Mira Infalível",resumo:"Desacelere o tempo para mirar em qualquer alvo como se ele estivesse parado.",custo:"CS",dados:"-",resist:"-",mecanica:"O alvo não pode realizar uma rolagem de defesa e seu ataque sempre tem dificuldade 1.",duracao:"Ataque"},
      {nivel:4,amalgama:"Ofus. 4",nome:"Golpe Imperceptível",resumo:"Desapareça e reapareça aplicando um golpe surpresa.",custo:"2 CS",dados:"Destreza + Celeridade",resist:"Raciocínio + Percepção",mecanica:"Se passar no teste, o ataque recebe os bônus de um ataque surpresa: o alvo não pode defender e você adiciona seu nível de Celeridade em sucessos.",duracao:"Ataque"},
      {nivel:5,amalgama:"-",nome:"Golpe Relâmpago",resumo:"Realize um ataque desarmado ou com armas brancas na velocidade do som.",custo:"CS",dados:"-",resist:"-",mecanica:"Não há teste para passar, o ataque causa dano sem permitir defesa ao alvo.",duracao:"Ataque"},
      {nivel:5,amalgama:"-",nome:"Fração de Segundos",resumo:"Sua velocidade é tão grande que você sente os eventos antes de eles acontecerem.",custo:"CS",dados:"-",resist:"-",mecanica:"Você pode interromper o narrador para retornar alguns segundos no tempo e mudar o que você fez ou realizar uma ação antes de que algo seja dito ou feito.",duracao:"Uma Ação"}
    ]
  },
  "Dominação": {
    descricao: "Disciplina do controle mental. Permite ao vampiro comandar mortais e vampiros, apagar memórias e reescrever a mente de suas vítimas.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Nublar Memória",resumo:"Faça alguém esquecer os últimos momentos vividos.",custo:"-",dados:"Carisma + Dominação",resist:"Raciocínio + Determinação",mecanica:"Nenhuma rolagem é necessária se o alvo for um mortal despreparado.",duracao:"Para Sempre"},
      {nivel:1,amalgama:"-",nome:"Compelir",resumo:"Emita um comando único e simples a um alvo.",custo:"-",dados:"Carisma + Dominação",resist:"Inteligência + Determinação",mecanica:"Nenhuma rolagem é necessária se o alvo for um mortal despreparado. O comando deve ser simples, com a mensagem transmitida em uma única sentença.",duracao:"Cena"},
      {nivel:1,amalgama:"Fort. 1",nome:"Devoção Eslávica",resumo:"Os alvos que estão sob seu Domínio resistem mais facilmente à tentativa de Domínio de outros vampiros.",custo:"-",dados:"-",resist:"-",mecanica:"Qualquer tentativa de teste sofre uma penalidade equivalente ao nível do usuário de Fortitude.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Impressionar",resumo:"Imponha comandos mais complexos.",custo:"CS",dados:"Manipulação + Dominação",resist:"Inteligência + Determinação",mecanica:"Nenhuma rolagem é necessária se o alvo for um mortal despreparado. Se o comando for contra sua natureza ou o fizer se ferir, ele pode rolar para resistir.",duracao:"-"},
      {nivel:2,amalgama:"Ofus. 2",nome:"Demência",resumo:"Leve a mente do alvo à insanidade temporariamente.",custo:"CS",dados:"Manipulação + Dominação",resist:"Autocontrole + Inteligência",mecanica:"Para conseguir usar esse poder o usuário deve estar tendo uma conversa estabelecida com o alvo, onde ele está focado.",duracao:"Cena"},
      {nivel:2,amalgama:"-",nome:"Favor do Domitor",resumo:"Torna extremamente difícil que alguém Enlaçado resista aos seus comandos.",custo:"CS",dados:"-",resist:"-",mecanica:"Ao usar a habilidade ela fica passiva no alvo durante um mês. Durante o mês, o Laço de Sangue não se enfraquece mesmo se não houver Beijo.",duracao:"Mês"},
      {nivel:3,amalgama:"-",nome:"Mente Elusiva",resumo:"Reescreva um detalhe de uma memória específica do alvo.",custo:"CS",dados:"Manipulação + Dominação",resist:"Inteligência + Determinação",mecanica:"Cada ponto de sucesso no teste permite que um detalhe ou uma memória a mais sejam atingidos.",duracao:"Para Sempre"},
      {nivel:3,amalgama:"-",nome:"Diretriz Submersa",resumo:"Implante uma ordem específica na mente de uma pessoa que persiste até ser completa.",custo:"-",dados:"-",resist:"-",mecanica:"Melhora a habilidade Impressionar para que o efeito só passe quando efetivamente houver realização da tarefa.",duracao:"-"},
      {nivel:4,amalgama:"Feit. 2",nome:"Domínio Ancestral",resumo:"Faça com que um vampiro aja da forma que você sugerir.",custo:"CS",dados:"Manipulação + Dominação",resist:"Inteligência + Determinação",mecanica:"Para cada geração de diferença o alvo ganha/perde um dado na hora de resistir.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Implantar Sugestão",resumo:"Mude a personalidade ou uma crença de um alvo temporariamente.",custo:"CS",dados:"Manipulação + Dominação",resist:"Autocontrole + Determinação",mecanica:"Nenhuma rolagem é necessária se o alvo for um mortal despreparado, a não ser que quebre uma crença muito sólida.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Racionalizar",resumo:"Convença as vítimas de sua Dominação de que foi ideia delas o tempo todo.",custo:"-",dados:"-",resist:"-",mecanica:"Não há mais confusão sobre o que aconteceu.",duracao:"-"},
      {nivel:4,amalgama:"-",nome:"Tabula Rasa",resumo:"Apague as memórias de alguém ao ponto de ele não saber mais quem era.",custo:"2 CS",dados:"Determinação + Dominação",resist:"Autocontrole + Determinação",mecanica:"O alvo não pode regredir a ponto de esquecer como fazer suas atividades básicas de sobrevivência.",duracao:"Para Sempre"},
      {nivel:5,amalgama:"-",nome:"O Chamado de Lethe",resumo:"Apague o equivalente a semanas da memória de alguém.",custo:"CS",dados:"Manipulação + Dominação",resist:"Inteligência + Determinação",mecanica:"Mortais não preparados não podem nem tentar resistir ao teste. Com comandos verbais o vampiro pode escolher que somente memórias de um tema específico sejam apagadas.",duracao:"Para Sempre"},
      {nivel:5,amalgama:"-",nome:"Manipulação em Massa",resumo:"Extenda o alcance de suas habilidades de Dominação para múltiplos alvos ao mesmo tempo.",custo:"CS",dados:"-",resist:"-",mecanica:"O alvo a resistir será o mais forte do grupo. Somente poderão ser afetadas vítimas que tiverem contato visual com o usuário.",duracao:"-"},
      {nivel:5,amalgama:"-",nome:"Decreto Final",resumo:"Melhora os efeitos de Dominação para poder ir contra crenças primordiais do alvo.",custo:"Mácula",dados:"-",resist:"-",mecanica:"Comandos de encerrar a própria vida são SEMPRE resistidos, independente do alvo.",duracao:"-"}
    ]
  },
  "Feitiçaria de Sangue": {
    descricao: "Disciplina da magia hemática. Permite ao vampiro manipular o sangue como arma, escudo e ferramenta para extrair segredos e alterar a realidade.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Vitae Corrosiva",resumo:"Transforma seu sangue em algo corrosivo.",custo:"CS",dados:"-",resist:"-",mecanica:"Não funciona contra pele de mortos-vivos e criaturas sobrenaturais. Somente materiais sólidos e pele humana.",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Molde o Sacramento",resumo:"Molde o sangue para formar um desenho ou escrita.",custo:"- / CS",dados:"Manipulação + Feitiçaria",resist:"-",mecanica:"Se utilizar o próprio sangue, custa um CS.",duracao:"Cena"},
      {nivel:1,amalgama:"-",nome:"Gosto por Sangue",resumo:"Ao provar sangue, descubra algumas características.",custo:"- / CS",dados:"Determinação + Feitiçaria",resist:"-",mecanica:"Descobre coisas como ressonância, potência, geração, criatura de origem e se o alvo já cometeu diablerie.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Maldição do Sangue",resumo:"Aumente a Perdição de outro vampiro.",custo:"CS",dados:"Inteligência + Feitiçaria",resist:"Vigor + Autocontrole",mecanica:"Aumente a penalidade em Dif.Teste.",duracao:"Até Dormir"},
      {nivel:2,amalgama:"-",nome:"Extinguir Vitae",resumo:"Aumente a fome de outro vampiro.",custo:"CS",dados:"Inteligência + Feitiçaria",resist:"Vigor + Autocontrole",mecanica:"A vítima pode descobrir quem usou a habilidade contra ela com um teste de Inteligência + Ocultismo.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Vasculhar Segredos",resumo:"Leia e aprenda uma vasta quantidade de conhecimento em segundos.",custo:"CS",dados:"Inteligência + Feitiçaria",resist:"-",mecanica:"O conteúdo precisa estar disponível de fácil acesso ao vampiro, seja em livros ou na internet.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Sangue de Potência",resumo:"Aumente a potência de sangue temporariamente.",custo:"CS",dados:"Determinação + Feitiçaria",resist:"-",mecanica:"Esse poder pode permitir que seja ultrapassado o limite estabelecido pela geração.",duracao:"Cena/Noite"},
      {nivel:3,amalgama:"-",nome:"Toque do Escorpião",resumo:"Transforma o próprio sangue em um veneno paralisante.",custo:"x CS",dados:"Força + Feitiçaria",resist:"Vigor + Ocultismo/Fortitude",mecanica:"Um mortal que sofrer com o veneno se torna inconsciente imediatamente. Vampiros que não passarem no teste são paralisados.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Laço Transitivo",resumo:"Aumenta as propriedades do laço de sangue.",custo:"CS",dados:"-",resist:"-",mecanica:"Torna mais fácil de realizar um abraço sem causar tantos danos ao alvo, ou no caso dos Tremere, torna possível novamente realizar um abraço.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Ondas Cardíacas",resumo:"Manipule um sangue específico para que o alvo que o consumir possa ser manipulado por você.",custo:"CS",dados:"-",resist:"-",mecanica:"Você pode imbuir compulsões específicas ao alvo, ou vontades/ideias.",duracao:"-"},
      {nivel:4,amalgama:"-",nome:"Roubo de Vitae",resumo:"Manipule o sangue de uma vítima a sair do corpo para que você se alimente.",custo:"CS",dados:"Raciocínio + Feitiçaria",resist:"Raciocínio + Ocultismo",mecanica:"Quando é um sucesso, a vítima entra no mesmo estado de torpor de um Beijo normal.",duracao:"Alimentação"},
      {nivel:4,amalgama:"-",nome:"Égide de Sangue",resumo:"Forme uma barreira protetora feita de sangue.",custo:"x CS",dados:"-",resist:"-",mecanica:"Para cada CS o usuário pode diminuir em até 5 pontos de dano tomados. Pode ser encerrada a qualquer momento.",duracao:"Cena"},
      {nivel:5,amalgama:"-",nome:"Carícia de Baal",resumo:"Transforma seu próprio sangue no mais mortal dos venenos.",custo:"x CS",dados:"Força + Feitiçaria",resist:"Vigor + Ocultismo/Fortitude",mecanica:"Se usado em um mortal ele morrerá ao tomar 1 ponto de dano. Ao usar em um Vampiro ele toma dano equivalente ao Dif.Teste.",duracao:"Cena"},
      {nivel:5,amalgama:"-",nome:"Caldeirão de Sangue",resumo:"Frite a vítima por dentro com seu próprio sangue.",custo:"CS + Mácula",dados:"Determinação + Feitiçaria",resist:"Autocontrole + Ocultismo/Fortitude",mecanica:"Se usado em um mortal ele morrerá ao tomar 1 ponto de dano. Ao usar em um Vampiro ele toma dano equivalente ao Dif.Teste.",duracao:"Turno"},
      {nivel:5,amalgama:"-",nome:"Reclamar Vitae",resumo:"Retire a propriedade Não Viva de Ghouls.",custo:"Mácula",dados:"-",resist:"-",mecanica:"Mesmo a distância, faça um ghoul retornar ao mundo dos mortos instantaneamente.",duracao:"-"}
    ]
  },
  "Fortitude": {
    descricao: "Disciplina da resistência sobrenatural. Permite ao vampiro suportar danos físicos e mentais que destruiriam qualquer outra criatura.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Resistência Fluente",resumo:"Rerrole seu CS em testes que envolvam Vigor ou Fortitude uma vez.",custo:"-",dados:"-",resist:"-",mecanica:"Uma única rerrolagem por teste.",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Resiliência",resumo:"Adicione seu nível de Fortitude na sua trilha de Vitalidade.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Mente Resiliente",resumo:"Adicione seu nível de Fortitude em testes de resistência mental.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Perseverança Pétrea",resumo:"Se torne uma rocha imóvel incapaz de tirarem do lugar.",custo:"CS",dados:"-",resist:"-",mecanica:"Apesar de não ser movível, ainda pode sofrer dano, assim como o solo aos seus pés também pode ser danificado.",duracao:"Cena"},
      {nivel:2,amalgama:"Anim. 1",nome:"Besta Vigorosa",resumo:"Divida sua resistência com seu familiar, tornando-o resistente.",custo:"CS",dados:"Vigor + Animalismo",resist:"-",mecanica:"O animal adiciona seu nível de Fortitude em testes de resistência e defesa.",duracao:"Cena"},
      {nivel:2,amalgama:"Ausp. 1",nome:"Vitae Envigorante",resumo:"Cura mortais mais rapidamente usando seu sangue.",custo:"CS",dados:"-",resist:"-",mecanica:"O risco de formar um Ghoul ou um Enlace ainda existem.",duracao:"-"},
      {nivel:2,amalgama:"Pot. 2",nome:"Obstinação",resumo:"Mantenha a postura ao ser atingido por forças externas.",custo:"CS",dados:"Vigor + Sobrevivência",resist:"-",mecanica:"Diminua o dano sofrido pela metade. Qualquer dano de queda é reduzido em seu nível de Fortitude antes de ser dividido pela metade.",duracao:"Cena"},
      {nivel:2,amalgama:"-",nome:"Dureza",resumo:"Subtraia sua Fortitude de qualquer dano que você tomar.",custo:"CS",dados:"-",resist:"-",mecanica:"Dividir por dois nunca pode resultar em valor menor do que 1.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Desafiar Perdição",resumo:"Converta qualquer dano Agravado tomado em dano Superficial.",custo:"CS",dados:"Raciocínio + Sobrevivência",resist:"-",mecanica:"Ao usar essa habilidade não é possível curar dano superficial durante o restante da cena.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Fortificar o Interior",resumo:"Aumenta a dificuldade para ações de domínio sobre sua mente em metade da sua Fortitude.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Selar a Mandíbula",resumo:"Você pode ignorar os dados de fome, porém se você falhar no CS sua parada de dados diminui equivalente.",custo:"2 CS",dados:"-",resist:"-",mecanica:"Se a parada de dados for reduzida a zero um Frenesi de Fúria se inicia.",duracao:"Cena"},
      {nivel:3,amalgama:"Ausp. 1",nome:"Valeren",resumo:"Cure um vampiro lesionado.",custo:"CS",dados:"Inteligência + Fortitude",resist:"-",mecanica:"Cure danos superficiais equivalentes aos sucessos. Sucessos críticos permitem cura de danos agravados igual a metade do valor. Um mesmo alvo não pode receber essa habilidade mais de uma vez por noite.",duracao:"-"},
      {nivel:4,amalgama:"-",nome:"Esboço do Vigor",resumo:"Transforme seu sangue em uma poção de vigor para os outros.",custo:"CS",dados:"-",resist:"-",mecanica:"Cada consumidor faz um teste de CS, eles recebem suas habilidades de Fortitude igual a metade do seu nível e todas as suas habilidades até o nível em questão.",duracao:"Noite"},
      {nivel:4,amalgama:"-",nome:"Escamas da Górgona",resumo:"Ressonâncias agora tem efeitos diferentes em você.",custo:"CS",dados:"-",resist:"-",mecanica:"Colérico te permite escapar de estacas. Melancólico reduz dano de fogo. Fleumático te fortalece contra Auspícios. Sanguíneo diminui dano de luz solar.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Estilhaçar",resumo:"Ao diminuir dano com Dureza, o alvo sofre esse dano.",custo:"CS",dados:"-",resist:"-",mecanica:"Armas de contato quebram caso seu nível seja igual ou maior ao dano recebido.",duracao:"Ataque"},
      {nivel:5,amalgama:"-",nome:"Carne de Mármore",resumo:"Ignore completamente a primeira fonte de dano que você tomar todo turno, que não seja de luz solar.",custo:"2CS",dados:"-",resist:"-",mecanica:"Sucessos críticos ignoram essa habilidade.",duracao:"Cena"},
      {nivel:5,amalgama:"-",nome:"Proeza pela Dor",resumo:"Ignore completamente suas penalidades por dano e aumente um atributo por quadrado de dano marcado.",custo:"CS",dados:"-",resist:"-",mecanica:"O atributo não pode ultrapassar um valor máximo de Potência de Sangue + 6.",duracao:"Cena"}
    ]
  },
  "Ofuscação": {
    descricao: "Disciplina do ocultamento e da ilusão. Permite ao vampiro tornar-se invisível, criar alucinações e manipular a percepção de suas vítimas.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Manto de Sombras",resumo:"Enquanto você permanecer parado, você fica extremamente difícil de ser percebido.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"Cena"},
      {nivel:1,amalgama:"-",nome:"Truque de Mãos",resumo:"Faça com que outros alvos ignorem completamente a presença de um objeto pequeno em suas mãos.",custo:"-",dados:"-",resist:"-",mecanica:"Sentir o Invisível pode burlar essa habilidade.",duracao:"Cena"},
      {nivel:1,amalgama:"-",nome:"Silêncio da Morte",resumo:"Elimine completamente o som que o usuário faz.",custo:"-",dados:"-",resist:"-",mecanica:"Sons causados por coisas externas ainda são gerados normalmente.",duracao:"Cena"},
      {nivel:2,amalgama:"-",nome:"Cache",resumo:"Esconda um objeto de tamanho médio que não precisa estar sendo segurado pelo usuário.",custo:"CS",dados:"-",resist:"-",mecanica:"Pode ter seu efeito estendido ao custo de mais CS.",duracao:"Cena"},
      {nivel:2,amalgama:"Pres. 1",nome:"Alquimerismo",resumo:"Crie uma curta, porém bastante realista, alucinação.",custo:"CS",dados:"Manipulação + Ofuscação",resist:"Autocontrole + Raciocínio",mecanica:"Pode ser usada durante combate, mas somente uma única vez por alvo.",duracao:"Turno"},
      {nivel:2,amalgama:"Anim. 1",nome:"Passagem Fantasmagórica",resumo:"O usuário pode tornar imperceptível a trilha deixada por um animal.",custo:"CS",dados:"-",resist:"-",mecanica:"Sentir o Invisível pode burlar essa habilidade.",duracao:"Sessão"},
      {nivel:2,amalgama:"-",nome:"Passagem Invisível",resumo:"O usuário agora pode se mover enquanto se mantém imperceptível.",custo:"CS",dados:"-",resist:"-",mecanica:"Essa habilidade vai falhar se antes de utilizada o usuário estiver sendo observado com atenção.",duracao:"Cena"},
      {nivel:2,amalgama:"Ausp. 2",nome:"Ventriloquismo",resumo:"Faça com que somente seu alvo ouça sua voz mesmo a distância.",custo:"CS",dados:"Raciocínio + Ofuscação",resist:"Determinação + Autocontrole",mecanica:"Pode ser usado em qualquer alvo, mas pode ser resistido.",duracao:"Cena"},
      {nivel:2,amalgama:"Ausp. 1",nome:"Fala Dupla",resumo:"Fale uma coisa em voz alta, mas faça com que seu alvo ouça uma mensagem diferente.",custo:"CS",dados:"Autocontrole + Ofuscação",resist:"Raciocínio + Auspícios",mecanica:"Qualquer pessoa presente que esteja focada na conversa pode tentar resistir para perceber a fala escondida.",duracao:"Fala"},
      {nivel:3,amalgama:"Pres. 2",nome:"Fata Morgana",resumo:"Transforme suas alucinações em coisas mais duradouras e elaboradas.",custo:"CS",dados:"Manipulação + Ofuscação",resist:"Autocontrole + Raciocínio",mecanica:"Somente pessoas muito conscientes ou vampiros podem resistir ao teste.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Fantasma na Máquina",resumo:"Permite que os efeitos de Ofuscação sejam transmitidos por tecnologia.",custo:"-",dados:"-",resist:"-",mecanica:"Se visto depois em uma foto ou vídeo, a imagem fica embaçada e difícil de discernir.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Máscara de Mil Faces",resumo:"Transforma sua aparência e presença como alguém qualquer aos outros.",custo:"CS",dados:"-",resist:"-",mecanica:"Esse poder permite que o usuário se comunique e interaja enquanto se mantém anônimo.",duracao:"Cena"},
      {nivel:3,amalgama:"Dom. 1",nome:"Máscara do Isolamento",resumo:"Force a habilidade Máscara de Mil Faces em um alvo.",custo:"CS",dados:"Manipulação + Ofuscação",resist:"Carisma + Sagacidade",mecanica:"Caso o usuário, por um motivo qualquer, se torne consciente do efeito, ele termina imediatamente.",duracao:"Noite"},
      {nivel:3,amalgama:"Dom. 1",nome:"Labirinto Mental",resumo:"Remova qualquer senso de direção e localização de um alvo.",custo:"1-3 CS",dados:"Carisma + Ofuscação",resist:"Raciocínio + Determinação",mecanica:"É necessário firmar contato visual. O custo varia de acordo com a familiaridade da pessoa com o local.",duracao:"Noite"},
      {nivel:3,amalgama:"Dom. 2",nome:"Fantasia da Mente",resumo:"Esconda e/ou troque as emoções visualizadas por poderes de invasão de mente.",custo:"CS",dados:"Inteligência + Ofuscação",resist:"-",mecanica:"A dificuldade do teste depende do quão complexa é a emoção que o usuário quer aparentar.",duracao:"Cena"},
      {nivel:4,amalgama:"Ausp. 3",nome:"Esconder",resumo:"Torne imperceptível um objeto inanimado.",custo:"CS",dados:"Inteligência + Ofuscação",resist:"-",mecanica:"Esse poder não pode afetar nada maior do que um sobrado ou algo que se mova por conta própria.",duracao:"Noite x Sucesso"},
      {nivel:4,amalgama:"-",nome:"Desaparecer",resumo:"Agora você pode ativar habilidades de sumiço mesmo quando é observado de perto.",custo:"-",dados:"Raciocínio + Ofuscação",resist:"Raciocínio + Percepção",mecanica:"Esse poder não afeta as memórias de vampiros, mas a visão fica nublada por alguns segundos quando você some.",duracao:"-"},
      {nivel:5,amalgama:"-",nome:"Manto da Unificação",resumo:"Usa um manto de sombras para esconder você e seus aliados.",custo:"Raciocínio + CS",dados:"-",resist:"-",mecanica:"Essa habilidade estende o efeito de ofuscações a um número de aliados equivalentes ao seu Raciocínio.",duracao:"-"},
      {nivel:5,amalgama:"-",nome:"Postura do Impostor",resumo:"Tenha a aparência convincente de outra pessoa.",custo:"CS",dados:"Raciocínio + Ofuscação",resist:"Manipulação + Performance",mecanica:"A face que será copiada deve ser estudada com atenção e visibilidade por pelo menos 5 minutos e por múltiplos ângulos.",duracao:"Cena"}
    ]
  },
  "Oblívio": {
    descricao: "Disciplina das trevas e da morte. Permite ao vampiro manipular sombras, interagir com o mundo espiritual e invocar o poder do esquecimento.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Do Pó ao Pó",resumo:"Destrua um corpo morto, dissolvendo-o.",custo:"CS",dados:"Vigor + Oblívio",resist:"Vigor + Medicina/Fortitude",mecanica:"Se o corpo não for algo reanimado, não há teste de resistência e em três turnos ele desaparece sem deixar rastros.",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Grilhões",resumo:"Permite que o vampiro identifique um Grilhão Sobrenatural.",custo:"-",dados:"Raciocínio + Oblívio",resist:"-",mecanica:"Durante o uso, o usuário recebe uma penalidade de -2 em Percepção, Raciocínio e Determinação.",duracao:"Cena"},
      {nivel:1,amalgama:"-",nome:"Visão do Oblívio",resumo:"Veja claramente na escuridão e perceba a presença de fantasmas.",custo:"-",dados:"-",resist:"-",mecanica:"Enquanto estiver usando, todos os atributos sociais recebem uma penalidade de -2.",duracao:"Cena"},
      {nivel:1,amalgama:"-",nome:"Manto Sombrio",resumo:"+2 de Bônus para testes de Furtividade e Intimidação contra mortais.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:2,amalgama:"Pot. 2",nome:"Braços de Ahriman",resumo:"Conjure apêndices de sombras que podem ser controlados e tangíveis, porém o usuário fica imóvel.",custo:"CS",dados:"Raciocínio + Oblívio",resist:"-",mecanica:"Os apêndices não têm trilha de vitalidade e conseguem ser escapados ou destruídos sem testes.",duracao:"Cena / Destruídos"},
      {nivel:2,amalgama:"Ausp. 2",nome:"Previsão Fatal",resumo:"Aumente a chance de que um mortal seja azarado e se lesione por forças externas.",custo:"CS",dados:"Determinação + Oblívio",resist:"Raciocínio + Ocultismo",mecanica:"Para cada sucesso além do teste de resistência o alvo recebe 1 de dano Agravado. O Vampiro não pode interagir com o alvo de forma alguma senão a habilidade é cancelada.",duracao:"24 Horas"},
      {nivel:2,amalgama:"Ausp. 2",nome:"Precognição Fatal",resumo:"Veja a forma como um ser mortal irá morrer.",custo:"CS",dados:"Determinação + Oblívio",resist:"-",mecanica:"O vampiro tem de conseguir enxergar ou ouvir o alvo para realizar a habilidade.",duracao:"Até completo ou evitado"},
      {nivel:2,amalgama:"-",nome:"Conjuração de Sombras",resumo:"Expande a sombra de seu corpo criando uma aura de penalidade no alvo afetado.",custo:"CS",dados:"-",resist:"-",mecanica:"Sua sombra pode se expandir até o dobro do seu nível de Oblívio em metros. Alvos sobre sua sombra sofrem penalidade de -2 em testes sociais.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Aura do Decaimento",resumo:"Usando sua conexão com o Oblívio você pode fazer plantas murcharem, animais e humanos adoecerem.",custo:"CS",dados:"Vigor + Oblívio",resist:"Vigor + Medicina/Fortitude",mecanica:"Comidas apodrecidas causam 2 de dano superficial. Pessoas e animais doentes recebem uma penalidade de -2 em Atributos Sociais.",duracao:"Cena"},
      {nivel:3,amalgama:"Fort. 2",nome:"Banquete da Paixão",resumo:"Permite que o vampiro satisfaça sua fome com a Paixão das Wraiths.",custo:"-",dados:"Determinação + Oblívio",resist:"Determinação + Autocontrole",mecanica:"A fome aliviada dura somente uma noite.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Perspectiva da Penumbra",resumo:"Projete algum de seus sentidos em qualquer sombra que esteja em sua linha de visão.",custo:"CS",dados:"-",resist:"-",mecanica:"Pode ser percebida com Perceber o Invisível.",duracao:"Cena"},
      {nivel:3,amalgama:"Ausp. 1",nome:"Servente Sombrio",resumo:"Use as sombras para espionar ou assustar o alvo.",custo:"CS",dados:"-",resist:"-",mecanica:"O Servente não tem uma consciência própria e é desfeito ao entrar em contato com um ambiente bastante iluminado.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Toque do Oblívio",resumo:"Murcha uma parte do corpo do alvo ao toque.",custo:"CS",dados:"-",resist:"-",mecanica:"O alvo deve estar sendo tocado pelo usuário. A depender do efeito realizado pode resultar em uma Mácula.",duracao:"Turno"},
      {nivel:4,amalgama:"-",nome:"Praga Necrótica",resumo:"Manifeste uma doença no alvo.",custo:"CS",dados:"Inteligência + Oblívio",resist:"Vigor + Medicina/Fortitude",mecanica:"A doença não pode ser tratada por meios médicos, somente irá passar ao consumir vitae.",duracao:"Turno / Duração"},
      {nivel:4,amalgama:"-",nome:"Manto Stígio",resumo:"Faça com que uma sombra em sua visão se espalhe criando uma área de total escuridão.",custo:"CS",dados:"-",resist:"-",mecanica:"A sombra pode aumentar a um tamanho de até duas vezes Oblívio metros.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Engate Umbral",resumo:"Usando a sombra da vítima, você cria um portal que a transporta até seus braços.",custo:"CS + Mácula",dados:"Raciocínio + Oblívio",resist:"Destreza + Raciocínio",mecanica:"Um mortal despreparado fica completamente apavorado sem reagir. Já um vampiro pode testar para Fúria ou Frenesi com dificuldade 4.",duracao:"Ação"},
      {nivel:5,amalgama:"-",nome:"Passo Sombrio",resumo:"O usuário pode entrar em uma sombra e reaparecer em outra dentro de sua linha de visão.",custo:"CS",dados:"-",resist:"-",mecanica:"Um alvo que concorde pode ser transportado junto do usuário.",duracao:"Turno"},
      {nivel:5,amalgama:"-",nome:"Dívida Paga",resumo:"Reintroduza uma doença da qual a vítima já havia se recuperado.",custo:"2 CS",dados:"Vigor + Oblívio",resist:"Vigor + Medicina/Fortitude",mecanica:"Se a vítima for um morto-vivo, essa habilidade remove o poder de não envelhecer e a criatura expele todo o vitae imediatamente.",duracao:"Variável"},
      {nivel:5,amalgama:"-",nome:"Avatar Tenebroso",resumo:"Transforma seu corpo em uma sombra capaz de se mover por qualquer superfície.",custo:"2 CS",dados:"-",resist:"-",mecanica:"O usuário não sofre dano nessa forma, com exceção de luz solar e fogo.",duracao:"Cena"},
      {nivel:5,amalgama:"-",nome:"Espírito a Murchar",resumo:"Destrói o espírito de um alvo até que ele se torne uma casca vazia.",custo:"2CS + Mácula",dados:"Determinação + Oblívio",resist:"Determinação + Ocultismo/Fortitude",mecanica:"-",duracao:"-"}
    ]
  },
  "Potência": {
    descricao: "Disciplina da força sobre-humana. Permite ao vampiro superar os limites físicos, causando dano devastador e realizando feitos impossíveis de força bruta.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Força Fluente",resumo:"Rerrole dados de CS uma única vez em testes de Força ou Potência.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Corpo Letal",resumo:"Ataques desarmados causam dano Agravado em mortais e ignoram 1 nível de armadura para cada nível de Potência.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:1,amalgama:"-",nome:"Salto Habilidoso",resumo:"Salte mais alto e mais longe do que o habitual.",custo:"-",dados:"-",resist:"-",mecanica:"Distância de até três vezes Potência em metros.",duracao:"-"},
      {nivel:2,amalgama:"-",nome:"Destreza",resumo:"Some Potência ao dano desarmado e metade de Potência em dano corpo a corpo armado.",custo:"CS",dados:"-",resist:"-",mecanica:"-",duracao:"Cena"},
      {nivel:2,amalgama:"-",nome:"Aperto Implacável",resumo:"Ganhe uma força de aperto sobrenatural.",custo:"CS",dados:"-",resist:"-",mecanica:"Alvos não conseguem se desvencilhar de você, a não ser que tenham força comparável.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Alimentação Brutal",resumo:"Transforme o ato de se alimentar em uma brutalidade excêntrica que dura míseros segundos.",custo:"-",dados:"-",resist:"-",mecanica:"Contra mortais é mecanicamente instantâneo. Contra vampiros, diminua pela metade o número de turnos que levaria.",duracao:"Alimentação"},
      {nivel:3,amalgama:"Pres. 3",nome:"Fagulha do Ódio",resumo:"O usuário pode adicionar Potência ao realizar ações de Intimidação ou Liderança.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Pegada Sinistra",resumo:"Fortalece ainda mais o aperto, permitindo que escale superfícies sólidas, se pendure no teto ou arranque pedaços de coisas fixas.",custo:"CS",dados:"-",resist:"-",mecanica:"O uso dessa habilidade deixa marcas muito claras.",duracao:"Cena"},
      {nivel:3,amalgama:"-",nome:"Destruidor",resumo:"Dobra o bônus de Potência em ações que envolvam Força ou Atletismo.",custo:"-",dados:"-",resist:"-",mecanica:"Não pode ser usada contra alvos mortais ou criaturas.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Rascunho da Força",resumo:"Transforma o próprio sangue em uma poção de força para outros vampiros.",custo:"CS",dados:"-",resist:"-",mecanica:"Cada vampiro que beber a poção deve fazer um CS. O alvo ganha nível de Potência igual à metade do usuário.",duracao:"Noite"},
      {nivel:4,amalgama:"-",nome:"Pouso Forçado",resumo:"Ao cair após usar Salto Habilidoso cause dano em área.",custo:"CS",dados:"Força + Potência",resist:"Destreza + Atletismo",mecanica:"Se a falha do oponente for de 3+, eles são derrubados.",duracao:"Ataque"},
      {nivel:5,amalgama:"-",nome:"Choque Terreno",resumo:"Atinge o chão e cria uma onda de choque.",custo:"2 CS",dados:"-",resist:"-",mecanica:"Todos os alvos atingidos são derrubados ao chão. Essa habilidade só pode ser utilizada uma única vez por cena.",duracao:"Ataque"},
      {nivel:5,amalgama:"-",nome:"Punho de Caim",resumo:"Inflige dano Agravado em mortais e criaturas sempre que causar dano.",custo:"CS",dados:"-",resist:"-",mecanica:"-",duracao:"Cena"},
      {nivel:5,amalgama:"-",nome:"Martelo Sutil",resumo:"Projeta toda sua força para um ponto específico do corpo do alvo.",custo:"-",dados:"-",resist:"-",mecanica:"Acertar partes do corpo com pouco movimento, como tronco, cabeça, abdome, fornece um bônus de +4 ao causar dano.",duracao:"-"}
    ]
  },
  "Presença": {
    descricao: "Disciplina da influência emocional. Permite ao vampiro fascinar, aterrorizar, seduzir e comandar multidões apenas com sua presença.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Admiração",resumo:"Adicione seu valor de Presença a qualquer teste envolvendo Persuasão, Performance ou Carisma.",custo:"-",dados:"-",resist:"-",mecanica:"Uma vez que o efeito termina, o alvo retorna a sua situação inicial de opinião.",duracao:"Cena"},
      {nivel:1,amalgama:"-",nome:"Assustar",resumo:"Adicione seu valor de Presença a qualquer teste envolvendo Intimidação.",custo:"-",dados:"-",resist:"-",mecanica:"Não pode ser utilizada ao mesmo tempo de Admiração e vice-versa.",duracao:"Cena"},
      {nivel:1,amalgama:"Protenismo. 1",nome:"Olhos da Serpente",resumo:"Imobilize a vítima ao fazer contato visual.",custo:"-",dados:"Carisma + Presença",resist:"Raciocínio + Autocontrole",mecanica:"Um alvo vampiro pode quebrar a paralisia ao gastar FdV em turnos subsequentes ao primeiro após a falha.",duracao:"Cena / Contato Visual"},
      {nivel:2,amalgama:"-",nome:"Beijo Persistente",resumo:"Ao realizar um Beijo ou se alimentar, você adiciona um bônus a atributos sociais da vítima.",custo:"-",dados:"-",resist:"-",mecanica:"O bônus é equivalente a metade da presença arredondada para cima, após o final da duração, a vítima sofre uma penalidade equivalente ao bônus por um período.",duracao:"Noites x Presença"},
      {nivel:2,amalgama:"-",nome:"Melpominee",resumo:"Use habilidades de presença sem precisar ver o alvo, somente usando sua voz.",custo:"-",dados:"-",resist:"-",mecanica:"Não funciona com habilidades que tenham alguma ativação específica como um Beijo.",duracao:"-"},
      {nivel:3,amalgama:"Dom. 3",nome:"Limpar a Área",resumo:"Acalme uma área e todos os mortais dentro dela.",custo:"CS",dados:"Autocontrole + Presença",resist:"Raciocínio + Autocontrole",mecanica:"Pode atingir um número de pessoas igual ao seu nível de Autocontrole.",duracao:"-"},
      {nivel:3,amalgama:"-",nome:"Olhar Putrefato",resumo:"Instigue medo em um alvo e faça com que ele tenha vontade de fugir.",custo:"CS",dados:"Carisma + Presença",resist:"Autocontrole + Determinação",mecanica:"Um crítico contra um alvo vampiro significa que o alvo faz um teste de Frenesi de Terror com dificuldade 3.",duracao:"Turno"},
      {nivel:3,amalgama:"-",nome:"Entrelaçamento",resumo:"Influencie alguém a entrar em um estado de mente que ele só pense na felicidade e prazer do usuário.",custo:"CS",dados:"Carisma + Presença",resist:"Raciocínio + Autocontrole",mecanica:"O usuário recebe bônus equivalente à sua Presença em testes sociais contra o alvo. Se um pedido que fira o alvo for feito, o teste precisa ser refeito.",duracao:"Hora"},
      {nivel:3,amalgama:"Ausp. 1",nome:"Voz Lançada",resumo:"Você pode arremessar sua voz ou deixar sua voz em um local, transmitindo uma mensagem ou uma habilidade.",custo:"CS",dados:"-",resist:"-",mecanica:"Uma rolagem somente é necessária equivalente à habilidade a ser usada pelo vampiro.",duracao:"Cena"},
      {nivel:3,amalgama:"Ofus. 3",nome:"Rosto do Amor Verdadeiro",resumo:"A vítima vai perceber o usuário como um mortal por quem ele tem fortes emoções.",custo:"CS",dados:"Manipulação + Presença",resist:"Autocontrole + Raciocínio",mecanica:"Pode gerar máculas caso dependa do nível de intimidade com a vítima e das ações sendo feitas.",duracao:"Cena"},
      {nivel:4,amalgama:"Dom. 1",nome:"Voz Irresistível",resumo:"A voz do usuário é suficiente para que use Dominação no alvo.",custo:"-",dados:"-",resist:"-",mecanica:"Não funciona através de tecnologia.",duracao:"-"},
      {nivel:4,amalgama:"Ausp. 3",nome:"Magnum Opus",resumo:"Imbua peças artísticas com sua Presença.",custo:"x CS",dados:"Carisma/Manipulação + Ofício",resist:"-",mecanica:"Plateias precisam rolar Autocontrole + Determinação para resistir aos seus efeitos.",duracao:"Objeto"},
      {nivel:4,amalgama:"-",nome:"Impregnar a Construção",resumo:"Aumente o alcance de sua Presença para todo um edifício.",custo:"-",dados:"-",resist:"-",mecanica:"Se o vampiro estiver presente, ele se torna o foco ao invés da construção.",duracao:"-"},
      {nivel:4,amalgama:"-",nome:"Invocar",resumo:"Convoque alguém até você que já tenha sofrido algum uso de sua Presença ou provou de seu vitae.",custo:"CS",dados:"Manipulação + Presença",resist:"Inteligência + Autocontrole",mecanica:"A vítima não se prejudica financeiramente ou se machuca para conseguir chegar até você.",duracao:"Noite"},
      {nivel:4,amalgama:"-",nome:"Parceiro",resumo:"Forneça alcance de sua Presença para que um aliado sirva como meio de transmissão.",custo:"CS",dados:"-",resist:"-",mecanica:"Caso dois usuários usem o mesmo poder de Presença, o efeito ainda é o de uso único, não há bônus.",duracao:"-"},
      {nivel:5,amalgama:"-",nome:"Majestade",resumo:"Todos que olharem para o usuário entram em choque e não conseguem agir a não ser que seja para se auto preservar.",custo:"2 CS",dados:"Carisma + Presença",resist:"Autocontrole + Determinação",mecanica:"Caso o teste de resistência seja vencedor, o alvo ganha 1 + Dif.Teste turnos para resistir, tendo que testar novamente após.",duracao:"Cena"},
      {nivel:5,amalgama:"-",nome:"Magnetismo Estelar",resumo:"Permite o uso de habilidades de Presença através de tecnologia, como transmissões de rádio ou TV.",custo:"CS extra",dados:"-",resist:"-",mecanica:"Não funciona em coisas gravadas, tem que ser ao vivo.",duracao:"-"}
    ]
  },
  "Proteanismo": {
    descricao: "Disciplina da transmutação física. Permite ao vampiro remodelar seu próprio corpo, transformar-se em animais e até mesmo derreter no solo.",
    habilidades: [
      {nivel:1,amalgama:"-",nome:"Olhar da Fera",resumo:"Permite que o usuário enxergue na escuridão completa.",custo:"-",dados:"-",resist:"-",mecanica:"Quando ativado também fornece +2 dados em testes de Intimidação contra mortais.",duracao:"Desejo"},
      {nivel:1,amalgama:"-",nome:"Peso Pena",resumo:"Transforma o peso do usuário em algo tão leve quanto uma pena.",custo:"-",dados:"Raciocínio + Sobrevivência",resist:"-",mecanica:"Parada de dados somente é utilizada quando ativada como reação, para diminuir a força de um impacto ou queda.",duracao:"Desejo"},
      {nivel:2,amalgama:"-",nome:"Armas Bestiais",resumo:"Prolongue suas unhas tornando-as garras.",custo:"CS",dados:"-",resist:"-",mecanica:"Adiciona +2 em rolagens de ataque desarmados.",duracao:"Cena"},
      {nivel:2,amalgama:"Dom. 2",nome:"Vicissitude",resumo:"Esculpa sua própria carne, modificando algum membro seu.",custo:"CS",dados:"Determinação + Proteanismo",resist:"-",mecanica:"Cada sucesso no teste permite uma 'unidade de mudança', a critério do narrador.",duracao:"Permanente"},
      {nivel:2,amalgama:"-",nome:"Beijo da Serpente",resumo:"Quando realizando um Beijo, você pode reinjetar o próprio sangue de volta na pessoa.",custo:"CS",dados:"-",resist:"-",mecanica:"Ativa ressonância e causa danos em habilidades de mutação de sangue da Feitiçaria de Sangue.",duracao:"Cena"},
      {nivel:2,amalgama:"Fort. 1",nome:"Gole Falso",resumo:"Previna completamente que sangue entre em seu organismo.",custo:"CS",dados:"-",resist:"-",mecanica:"O sangue deve ser regurgitado ao final da cena, ou durar mais uma cena ao custo de mais um CS.",duracao:"Cena +"},
      {nivel:3,amalgama:"-",nome:"Derreter à Terra",resumo:"Derreta, se juntando ao solo.",custo:"CS",dados:"-",resist:"-",mecanica:"Só pode ser usado em superfícies naturais ou artificiais porosas, como asfalto. O vampiro pode ficar nessa forma por até um dia ou até ser perturbado.",duracao:"Depende"},
      {nivel:3,amalgama:"Dom. 2",nome:"Moldar a Carne",resumo:"Expanda o uso de Vicissitude para ser usado em corpos terceiros.",custo:"CS",dados:"Determinação + Proteanismo",resist:"Vigor + Determinação",mecanica:"Teste só é feito em um alvo que não quer ser submetido ao procedimento. Mesmas regras de Vicissitude se aplicam aqui.",duracao:"Permanente"},
      {nivel:3,amalgama:"-",nome:"Transformação",resumo:"Se transforme em um animal de massa próxima a sua.",custo:"CS",dados:"-",resist:"-",mecanica:"Usuário ganha os atributos físicos equivalentes ao do animal escolhido.",duracao:"Cena"},
      {nivel:3,amalgama:"Feit. 2",nome:"Absorção Visceral",resumo:"Absorva os restos mortais de sangue ou de mortos-vivos, para limpar completamente a cena.",custo:"CS",dados:"Força + Proteanismo",resist:"-",mecanica:"Fome pode ser reduzida em 1 para cada corpo absorvido, mas nunca a zero.",duracao:"Um turno por corpo"},
      {nivel:4,amalgama:"Dom. 2",nome:"Forma Horripilante",resumo:"Se transforme em um corpo monstruoso.",custo:"CS",dados:"-",resist:"-",mecanica:"Mudanças equivalentes ao nível de Proteanismo do usuário, qualquer crítico nesse teste é considerado um Crítico Bestial.",duracao:"Cena"},
      {nivel:4,amalgama:"-",nome:"Metamorfose",resumo:"Melhora Transformação para poder se tornar um animal ainda maior.",custo:"CS",dados:"-",resist:"-",mecanica:"Mesmas regras se aplicam.",duracao:"-"},
      {nivel:5,amalgama:"Feit. 2",nome:"Forma do Sangue",resumo:"Se transforme em uma massa amorfa de sangue.",custo:"CS",dados:"-",resist:"-",mecanica:"Pode ser consumido, criando laços de sangue. Pode ser percebido a depender do teste do usuário de Raciocínio + Percepção.",duracao:"Cena"},
      {nivel:5,amalgama:"Fort. 2",nome:"Coração das Trevas",resumo:"Permite que um vampiro retire seu próprio coração e o armazene em um local adequado.",custo:"-",dados:"-",resist:"-",mecanica:"Coração só pode ser destruído por fogo ou luz solar. Se tomar dano equivalente à trilha de vitalidade do vampiro, ele entra em torpor.",duracao:"Eterno"},
      {nivel:5,amalgama:"-",nome:"Mestre das Formas",resumo:"Permite que o vampiro se torne qualquer forma animal e até mesmo de vários animais ao mesmo tempo.",custo:"CS",dados:"-",resist:"-",mecanica:"-",duracao:"-"},
      {nivel:5,amalgama:"-",nome:"Névoa",resumo:"Se transforme em uma nuvem de névoa.",custo:"1-3 CS",dados:"-",resist:"-",mecanica:"Essa habilidade leva até 3 turnos para se completar, mas pode ser acelerada com uso de mais CS.",duracao:"Cena"},
      {nivel:5,amalgama:"Anim. 2",nome:"Um com a Terra",resumo:"Melhora a habilidade Derreter à Terra. Agora o vampiro não tem limitantes de material.",custo:"2 CS",dados:"-",resist:"-",mecanica:"Vampiro agora pode se misturar à qualquer tipo de superfície, até mesmo vertical.",duracao:"Dia"},
      {nivel:5,amalgama:"-",nome:"Coração Irrestrito",resumo:"O coração retirado do vampiro agora se move dificultando dano.",custo:"-",dados:"-",resist:"-",mecanica:"-",duracao:"-"}
    ]
  }
};
